/* Generated by Yosys 0.7+560 (git sha1 d9a2b430, gcc 7.3.1 -fPIC -Os) */

module ffd_p2s_synth_delay(CLK, D, ENB, valid_in, Q, valid_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input CLK;
  input D;
  input ENB;
  output Q;
  reg Q;
  input valid_in;
  output valid_out;
  NOT_delay _05_ (
    .A(D),
    .Y(_01_)
  );
  NOR_delay _06_ (
    .A(Q),
    .B(valid_in),
    .Y(_02_)
  );
  NAND_delay _07_ (
    .A(_01_),
    .B(valid_in),
    .Y(_03_)
  );
  NAND_delay _08_ (
    .A(ENB),
    .B(_03_),
    .Y(_04_)
  );
  NOR_delay _09_ (
    .A(_02_),
    .B(_04_),
    .Y(_00_)
  );
  always @(posedge CLK)
      Q <= #15  _00_;
  assign valid_out = 1'h1;
endmodule
