/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-10 -O2 -fdebug-prefix-map=/build/yosys-0DEyT5/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module ffd_p2s_synth_delay(CLK, D, ENB, Q);
  wire _0_;
  wire _1_;
  wire _2_;
  input CLK;
  input D;
  input ENB;
  output Q;
  reg Q;
  NOT_delay _3_ (
    .A(D),
    .Y(_1_)
  );
  NOT_delay _4_ (
    .A(ENB),
    .Y(_2_)
  );
  NOR_delay _5_ (
    .A(_2_),
    .B(_1_),
    .Y(_0_)
  );
  always @(posedge CLK)
      Q <= #15  _0_;
endmodule
