/* Generated by Yosys 0.7 (git sha1 UNKNOWN, clang 5.0.1 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -fPIC -Os) */

module freq_div_synth(CLK, reset, CLK_2, CLK_4, CLK_8);
  wire _0_;
  wire _1_;
  input CLK;
  output CLK_2;
  reg CLK_2;
  output CLK_4;
  output CLK_8;
  input reset;
  NOT _2_ (
    .A(reset),
    .Y(_1_)
  );
  NOR _3_ (
    .A(CLK_2),
    .B(_1_),
    .Y(_0_)
  );
  always @(posedge CLK)
      CLK_2 <= _0_;
  assign CLK_4 = 1'b0;
  assign CLK_8 = 1'b0;
endmodule
