/* Generated by Yosys 0.7 (git sha1 UNKNOWN, clang 5.0.1 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -fPIC -Os) */

module registro_4yosys(Q, S_OUT, D, MODO, CLK, ENB, DIR, S_IN);
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  input CLK;
  input [3:0] D;
  input DIR;
  input ENB;
  input [1:0] MODO;
  output [3:0] Q;
  reg [3:0] Q;
  input S_IN;
  output S_OUT;
  reg S_OUT;
  NOR _053_ (
    .A(ENB),
    .B(Q[0]),
    .Y(_002_)
  );
  NOT _054_ (
    .A(MODO[0]),
    .Y(_003_)
  );
  NOR _055_ (
    .A(_003_),
    .B(MODO[1]),
    .Y(_004_)
  );
  NAND _056_ (
    .A(DIR),
    .B(Q[1]),
    .Y(_005_)
  );
  NOT _057_ (
    .A(DIR),
    .Y(_006_)
  );
  NAND _058_ (
    .A(Q[3]),
    .B(_006_),
    .Y(_007_)
  );
  NAND _059_ (
    .A(_007_),
    .B(_005_),
    .Y(_008_)
  );
  NAND _060_ (
    .A(_008_),
    .B(_004_),
    .Y(_009_)
  );
  NAND _061_ (
    .A(D[0]),
    .B(MODO[1]),
    .Y(_010_)
  );
  NAND _062_ (
    .A(_010_),
    .B(_009_),
    .Y(_011_)
  );
  NOR _063_ (
    .A(MODO[0]),
    .B(MODO[1]),
    .Y(_012_)
  );
  NAND _064_ (
    .A(_006_),
    .B(S_IN),
    .Y(_013_)
  );
  NAND _065_ (
    .A(_013_),
    .B(_005_),
    .Y(_014_)
  );
  NAND _066_ (
    .A(_014_),
    .B(_012_),
    .Y(_015_)
  );
  NAND _067_ (
    .A(_015_),
    .B(ENB),
    .Y(_016_)
  );
  NOR _068_ (
    .A(_016_),
    .B(_011_),
    .Y(_017_)
  );
  NOR _069_ (
    .A(_017_),
    .B(_002_),
    .Y(_000_[0])
  );
  NAND _070_ (
    .A(D[1]),
    .B(MODO[1]),
    .Y(_018_)
  );
  NOT _071_ (
    .A(MODO[1]),
    .Y(_019_)
  );
  NAND _072_ (
    .A(Q[0]),
    .B(_006_),
    .Y(_020_)
  );
  NAND _073_ (
    .A(Q[2]),
    .B(DIR),
    .Y(_021_)
  );
  NAND _074_ (
    .A(_021_),
    .B(_020_),
    .Y(_022_)
  );
  NAND _075_ (
    .A(_022_),
    .B(_019_),
    .Y(_023_)
  );
  NAND _076_ (
    .A(_023_),
    .B(_018_),
    .Y(_024_)
  );
  NAND _077_ (
    .A(_024_),
    .B(ENB),
    .Y(_025_)
  );
  NOT _078_ (
    .A(ENB),
    .Y(_026_)
  );
  NAND _079_ (
    .A(_026_),
    .B(Q[1]),
    .Y(_027_)
  );
  NAND _080_ (
    .A(_027_),
    .B(_025_),
    .Y(_000_[1])
  );
  NAND _081_ (
    .A(D[2]),
    .B(MODO[1]),
    .Y(_028_)
  );
  NAND _082_ (
    .A(_006_),
    .B(Q[1]),
    .Y(_029_)
  );
  NAND _083_ (
    .A(Q[3]),
    .B(DIR),
    .Y(_030_)
  );
  NAND _084_ (
    .A(_030_),
    .B(_029_),
    .Y(_031_)
  );
  NAND _085_ (
    .A(_031_),
    .B(_019_),
    .Y(_032_)
  );
  NAND _086_ (
    .A(_032_),
    .B(_028_),
    .Y(_033_)
  );
  NAND _087_ (
    .A(_033_),
    .B(ENB),
    .Y(_034_)
  );
  NAND _088_ (
    .A(_026_),
    .B(Q[2]),
    .Y(_035_)
  );
  NAND _089_ (
    .A(_035_),
    .B(_034_),
    .Y(_000_[2])
  );
  NOR _090_ (
    .A(ENB),
    .B(Q[3]),
    .Y(_036_)
  );
  NAND _091_ (
    .A(Q[2]),
    .B(_006_),
    .Y(_037_)
  );
  NAND _092_ (
    .A(Q[0]),
    .B(DIR),
    .Y(_038_)
  );
  NAND _093_ (
    .A(_038_),
    .B(_037_),
    .Y(_039_)
  );
  NAND _094_ (
    .A(_039_),
    .B(_004_),
    .Y(_040_)
  );
  NAND _095_ (
    .A(D[3]),
    .B(MODO[1]),
    .Y(_041_)
  );
  NAND _096_ (
    .A(_041_),
    .B(_040_),
    .Y(_042_)
  );
  NAND _097_ (
    .A(DIR),
    .B(S_IN),
    .Y(_043_)
  );
  NAND _098_ (
    .A(_043_),
    .B(_037_),
    .Y(_044_)
  );
  NAND _099_ (
    .A(_044_),
    .B(_012_),
    .Y(_045_)
  );
  NAND _100_ (
    .A(_045_),
    .B(ENB),
    .Y(_046_)
  );
  NOR _101_ (
    .A(_046_),
    .B(_042_),
    .Y(_047_)
  );
  NOR _102_ (
    .A(_047_),
    .B(_036_),
    .Y(_000_[3])
  );
  NAND _103_ (
    .A(S_OUT),
    .B(_026_),
    .Y(_048_)
  );
  NAND _104_ (
    .A(_038_),
    .B(_007_),
    .Y(_049_)
  );
  NOT _105_ (
    .A(_012_),
    .Y(_050_)
  );
  NOR _106_ (
    .A(_050_),
    .B(_026_),
    .Y(_051_)
  );
  NAND _107_ (
    .A(_051_),
    .B(_049_),
    .Y(_052_)
  );
  NAND _108_ (
    .A(_052_),
    .B(_048_),
    .Y(_001_)
  );
  always @(posedge CLK)
      Q[0] <= _000_[0];
  always @(posedge CLK)
      Q[1] <= _000_[1];
  always @(posedge CLK)
      Q[2] <= _000_[2];
  always @(posedge CLK)
      Q[3] <= _000_[3];
  always @(posedge CLK)
      S_OUT <= _001_;
endmodule
