/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

module byte_striping_struct(stripedLane0, stripedLane1, stripedLane2, stripedLane3, byteStripingVLD, byteStripingIN, lane0VLD, lane1VLD, lane2VLD, lane3VLD, clk250k, clk1Mhz, counter, reset);
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  input [7:0] byteStripingIN;
  output byteStripingVLD;
  input clk1Mhz;
  input clk250k;
  output [1:0] counter;
  input lane0VLD;
  input lane1VLD;
  input lane2VLD;
  input lane3VLD;
  input reset;
  output [7:0] stripedLane0;
  reg [7:0] stripedLane0;
  output [7:0] stripedLane1;
  output [7:0] stripedLane2;
  output [7:0] stripedLane3;
  NAND _18_ (
    .A(lane0VLD),
    .B(byteStripingIN[0]),
    .Y(_01_)
  );
  NOT _19_ (
    .A(lane0VLD),
    .Y(_02_)
  );
  NAND _20_ (
    .A(_02_),
    .B(stripedLane0[0]),
    .Y(_03_)
  );
  NAND _21_ (
    .A(_03_),
    .B(_01_),
    .Y(_00_[0])
  );
  NAND _22_ (
    .A(byteStripingIN[1]),
    .B(lane0VLD),
    .Y(_04_)
  );
  NAND _23_ (
    .A(stripedLane0[1]),
    .B(_02_),
    .Y(_05_)
  );
  NAND _24_ (
    .A(_05_),
    .B(_04_),
    .Y(_00_[1])
  );
  NAND _25_ (
    .A(byteStripingIN[2]),
    .B(lane0VLD),
    .Y(_06_)
  );
  NAND _26_ (
    .A(stripedLane0[2]),
    .B(_02_),
    .Y(_07_)
  );
  NAND _27_ (
    .A(_07_),
    .B(_06_),
    .Y(_00_[2])
  );
  NAND _28_ (
    .A(byteStripingIN[3]),
    .B(lane0VLD),
    .Y(_08_)
  );
  NAND _29_ (
    .A(stripedLane0[3]),
    .B(_02_),
    .Y(_09_)
  );
  NAND _30_ (
    .A(_09_),
    .B(_08_),
    .Y(_00_[3])
  );
  NAND _31_ (
    .A(byteStripingIN[4]),
    .B(lane0VLD),
    .Y(_10_)
  );
  NAND _32_ (
    .A(stripedLane0[4]),
    .B(_02_),
    .Y(_11_)
  );
  NAND _33_ (
    .A(_11_),
    .B(_10_),
    .Y(_00_[4])
  );
  NAND _34_ (
    .A(byteStripingIN[5]),
    .B(lane0VLD),
    .Y(_12_)
  );
  NAND _35_ (
    .A(stripedLane0[5]),
    .B(_02_),
    .Y(_13_)
  );
  NAND _36_ (
    .A(_13_),
    .B(_12_),
    .Y(_00_[5])
  );
  NAND _37_ (
    .A(byteStripingIN[6]),
    .B(lane0VLD),
    .Y(_14_)
  );
  NAND _38_ (
    .A(stripedLane0[6]),
    .B(_02_),
    .Y(_15_)
  );
  NAND _39_ (
    .A(_15_),
    .B(_14_),
    .Y(_00_[6])
  );
  NAND _40_ (
    .A(byteStripingIN[7]),
    .B(lane0VLD),
    .Y(_16_)
  );
  NAND _41_ (
    .A(stripedLane0[7]),
    .B(_02_),
    .Y(_17_)
  );
  NAND _42_ (
    .A(_17_),
    .B(_16_),
    .Y(_00_[7])
  );
  always @(posedge clk1Mhz)
      stripedLane0[0] <= _00_[0];
  always @(posedge clk1Mhz)
      stripedLane0[1] <= _00_[1];
  always @(posedge clk1Mhz)
      stripedLane0[2] <= _00_[2];
  always @(posedge clk1Mhz)
      stripedLane0[3] <= _00_[3];
  always @(posedge clk1Mhz)
      stripedLane0[4] <= _00_[4];
  always @(posedge clk1Mhz)
      stripedLane0[5] <= _00_[5];
  always @(posedge clk1Mhz)
      stripedLane0[6] <= _00_[6];
  always @(posedge clk1Mhz)
      stripedLane0[7] <= _00_[7];
  assign byteStripingVLD = 1'b0;
  assign counter = 2'b00;
endmodule
