/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "byte_striping_struct.v:1" *)
module byte_striping_struct(stripedLane0, stripedLane1, stripedLane2, stripedLane3, byteStripingVLD, byteStripingIN, lane0VLD, lane1VLD, lane2VLD, lane3VLD, clk250k, clk1Mhz, counter, reset);
  (* src = "byte_striping_struct.v:19" *)
  wire _000_;
  (* src = "byte_striping_struct.v:19" *)
  wire [1:0] _001_;
  (* src = "byte_striping_struct.v:19" *)
  wire [7:0] _002_;
  (* src = "byte_striping_struct.v:19" *)
  wire [7:0] _003_;
  (* src = "byte_striping_struct.v:19" *)
  wire [7:0] _004_;
  (* src = "byte_striping_struct.v:19" *)
  wire [7:0] _005_;
  (* src = "byte_striping_struct.v:23" *)
  wire [31:0] _006_;
  wire [1:0] _007_;
  wire [1:0] _008_;
  wire _009_;
  wire [1:0] _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire [7:0] _021_;
  wire [7:0] _022_;
  wire [7:0] _023_;
  wire [7:0] _024_;
  wire _025_;
  (* src = "byte_striping_struct.v:26|<techmap.v>:432" *)
  wire [3:0] _026_;
  (* src = "byte_striping_struct.v:26|<techmap.v>:428" *)
  wire _027_;
  (* src = "byte_striping_struct.v:26|<techmap.v>:445" *)
  wire _028_;
  (* src = "byte_striping_struct.v:8" *)
  input [7:0] byteStripingIN;
  (* src = "byte_striping_struct.v:6" *)
  output byteStripingVLD;
  reg byteStripingVLD;
  (* src = "byte_striping_struct.v:14" *)
  input clk1Mhz;
  (* src = "byte_striping_struct.v:13" *)
  input clk250k;
  (* src = "byte_striping_struct.v:15" *)
  output [1:0] counter;
  reg [1:0] counter;
  (* src = "byte_striping_struct.v:9" *)
  input lane0VLD;
  (* src = "byte_striping_struct.v:10" *)
  input lane1VLD;
  (* src = "byte_striping_struct.v:11" *)
  input lane2VLD;
  (* src = "byte_striping_struct.v:12" *)
  input lane3VLD;
  (* src = "byte_striping_struct.v:16" *)
  input reset;
  (* src = "byte_striping_struct.v:2" *)
  output [7:0] stripedLane0;
  reg [7:0] stripedLane0;
  (* src = "byte_striping_struct.v:3" *)
  output [7:0] stripedLane1;
  reg [7:0] stripedLane1;
  (* src = "byte_striping_struct.v:4" *)
  output [7:0] stripedLane2;
  reg [7:0] stripedLane2;
  (* src = "byte_striping_struct.v:5" *)
  output [7:0] stripedLane3;
  reg [7:0] stripedLane3;
  assign _011_ = _006_[0] |(* src = "byte_striping_struct.v:26" *)  _010_[1];
  assign _012_ = counter[0] |(* src = "byte_striping_struct.v:26" *)  _010_[1];
  assign _013_ = _006_[0] |(* src = "byte_striping_struct.v:26" *)  counter[1];
  assign _007_[0] = _026_[0] |(* src = "byte_striping_struct.v:26|<techmap.v>:441" *)  _026_[1];
  assign _007_[1] = _026_[2] |(* src = "byte_striping_struct.v:26|<techmap.v>:441" *)  _026_[3];
  assign _027_ = _007_[0] |(* src = "byte_striping_struct.v:26|<techmap.v>:441" *)  _007_[1];
  assign _008_[0] = _014_ |(* src = "byte_striping_struct.v:26|<techmap.v>:445" *)  _016_;
  assign _008_[1] = _018_ |(* src = "byte_striping_struct.v:26|<techmap.v>:445" *)  _020_;
  assign _028_ = _008_[0] |(* src = "byte_striping_struct.v:26|<techmap.v>:445" *)  _008_[1];
  assign _009_ = counter[0] |(* src = "byte_striping_struct.v:26" *)  counter[1];
  assign _014_ = ~(* src = "byte_striping_struct.v:26" *) _011_;
  assign _016_ = ~(* src = "byte_striping_struct.v:26" *) _012_;
  assign _018_ = ~(* src = "byte_striping_struct.v:26" *) _013_;
  assign _020_ = ~(* src = "byte_striping_struct.v:26" *) _009_;
  assign _001_[0] = reset ? (* src = "byte_striping_struct.v:20" *) 1'b0 : _006_[0];
  assign _001_[1] = reset ? (* src = "byte_striping_struct.v:20" *) 1'b0 : _006_[1];
  assign _025_ = lane3VLD ? (* src = "byte_striping_struct.v:42" *) 1'b1 : byteStripingVLD;
  assign _015_ = lane2VLD ? (* src = "byte_striping_struct.v:37" *) 1'b0 : byteStripingVLD;
  assign _017_ = lane1VLD ? (* src = "byte_striping_struct.v:32" *) 1'b0 : byteStripingVLD;
  assign _019_ = lane0VLD ? (* src = "byte_striping_struct.v:27" *) 1'b0 : byteStripingVLD;
  assign _021_[0] = lane3VLD ? (* src = "byte_striping_struct.v:42" *) byteStripingIN[0] : stripedLane3[0];
  assign _021_[1] = lane3VLD ? (* src = "byte_striping_struct.v:42" *) byteStripingIN[1] : stripedLane3[1];
  assign _021_[2] = lane3VLD ? (* src = "byte_striping_struct.v:42" *) byteStripingIN[2] : stripedLane3[2];
  assign _021_[3] = lane3VLD ? (* src = "byte_striping_struct.v:42" *) byteStripingIN[3] : stripedLane3[3];
  assign _021_[4] = lane3VLD ? (* src = "byte_striping_struct.v:42" *) byteStripingIN[4] : stripedLane3[4];
  assign _021_[5] = lane3VLD ? (* src = "byte_striping_struct.v:42" *) byteStripingIN[5] : stripedLane3[5];
  assign _021_[6] = lane3VLD ? (* src = "byte_striping_struct.v:42" *) byteStripingIN[6] : stripedLane3[6];
  assign _021_[7] = lane3VLD ? (* src = "byte_striping_struct.v:42" *) byteStripingIN[7] : stripedLane3[7];
  assign _005_[0] = _011_ ? (* src = "byte_striping_struct.v:26" *) stripedLane3[0] : _021_[0];
  assign _005_[1] = _011_ ? (* src = "byte_striping_struct.v:26" *) stripedLane3[1] : _021_[1];
  assign _005_[2] = _011_ ? (* src = "byte_striping_struct.v:26" *) stripedLane3[2] : _021_[2];
  assign _005_[3] = _011_ ? (* src = "byte_striping_struct.v:26" *) stripedLane3[3] : _021_[3];
  assign _005_[4] = _011_ ? (* src = "byte_striping_struct.v:26" *) stripedLane3[4] : _021_[4];
  assign _005_[5] = _011_ ? (* src = "byte_striping_struct.v:26" *) stripedLane3[5] : _021_[5];
  assign _005_[6] = _011_ ? (* src = "byte_striping_struct.v:26" *) stripedLane3[6] : _021_[6];
  assign _005_[7] = _011_ ? (* src = "byte_striping_struct.v:26" *) stripedLane3[7] : _021_[7];
  assign _022_[0] = lane2VLD ? (* src = "byte_striping_struct.v:37" *) byteStripingIN[0] : stripedLane2[0];
  assign _022_[1] = lane2VLD ? (* src = "byte_striping_struct.v:37" *) byteStripingIN[1] : stripedLane2[1];
  assign _022_[2] = lane2VLD ? (* src = "byte_striping_struct.v:37" *) byteStripingIN[2] : stripedLane2[2];
  assign _022_[3] = lane2VLD ? (* src = "byte_striping_struct.v:37" *) byteStripingIN[3] : stripedLane2[3];
  assign _022_[4] = lane2VLD ? (* src = "byte_striping_struct.v:37" *) byteStripingIN[4] : stripedLane2[4];
  assign _022_[5] = lane2VLD ? (* src = "byte_striping_struct.v:37" *) byteStripingIN[5] : stripedLane2[5];
  assign _022_[6] = lane2VLD ? (* src = "byte_striping_struct.v:37" *) byteStripingIN[6] : stripedLane2[6];
  assign _022_[7] = lane2VLD ? (* src = "byte_striping_struct.v:37" *) byteStripingIN[7] : stripedLane2[7];
  assign _004_[0] = _012_ ? (* src = "byte_striping_struct.v:26" *) stripedLane2[0] : _022_[0];
  assign _004_[1] = _012_ ? (* src = "byte_striping_struct.v:26" *) stripedLane2[1] : _022_[1];
  assign _004_[2] = _012_ ? (* src = "byte_striping_struct.v:26" *) stripedLane2[2] : _022_[2];
  assign _004_[3] = _012_ ? (* src = "byte_striping_struct.v:26" *) stripedLane2[3] : _022_[3];
  assign _004_[4] = _012_ ? (* src = "byte_striping_struct.v:26" *) stripedLane2[4] : _022_[4];
  assign _004_[5] = _012_ ? (* src = "byte_striping_struct.v:26" *) stripedLane2[5] : _022_[5];
  assign _004_[6] = _012_ ? (* src = "byte_striping_struct.v:26" *) stripedLane2[6] : _022_[6];
  assign _004_[7] = _012_ ? (* src = "byte_striping_struct.v:26" *) stripedLane2[7] : _022_[7];
  assign _023_[0] = lane1VLD ? (* src = "byte_striping_struct.v:32" *) byteStripingIN[0] : stripedLane1[0];
  assign _023_[1] = lane1VLD ? (* src = "byte_striping_struct.v:32" *) byteStripingIN[1] : stripedLane1[1];
  assign _023_[2] = lane1VLD ? (* src = "byte_striping_struct.v:32" *) byteStripingIN[2] : stripedLane1[2];
  assign _023_[3] = lane1VLD ? (* src = "byte_striping_struct.v:32" *) byteStripingIN[3] : stripedLane1[3];
  assign _023_[4] = lane1VLD ? (* src = "byte_striping_struct.v:32" *) byteStripingIN[4] : stripedLane1[4];
  assign _023_[5] = lane1VLD ? (* src = "byte_striping_struct.v:32" *) byteStripingIN[5] : stripedLane1[5];
  assign _023_[6] = lane1VLD ? (* src = "byte_striping_struct.v:32" *) byteStripingIN[6] : stripedLane1[6];
  assign _023_[7] = lane1VLD ? (* src = "byte_striping_struct.v:32" *) byteStripingIN[7] : stripedLane1[7];
  assign _003_[0] = _013_ ? (* src = "byte_striping_struct.v:26" *) stripedLane1[0] : _023_[0];
  assign _003_[1] = _013_ ? (* src = "byte_striping_struct.v:26" *) stripedLane1[1] : _023_[1];
  assign _003_[2] = _013_ ? (* src = "byte_striping_struct.v:26" *) stripedLane1[2] : _023_[2];
  assign _003_[3] = _013_ ? (* src = "byte_striping_struct.v:26" *) stripedLane1[3] : _023_[3];
  assign _003_[4] = _013_ ? (* src = "byte_striping_struct.v:26" *) stripedLane1[4] : _023_[4];
  assign _003_[5] = _013_ ? (* src = "byte_striping_struct.v:26" *) stripedLane1[5] : _023_[5];
  assign _003_[6] = _013_ ? (* src = "byte_striping_struct.v:26" *) stripedLane1[6] : _023_[6];
  assign _003_[7] = _013_ ? (* src = "byte_striping_struct.v:26" *) stripedLane1[7] : _023_[7];
  assign _024_[0] = lane0VLD ? (* src = "byte_striping_struct.v:27" *) byteStripingIN[0] : stripedLane0[0];
  assign _024_[1] = lane0VLD ? (* src = "byte_striping_struct.v:27" *) byteStripingIN[1] : stripedLane0[1];
  assign _024_[2] = lane0VLD ? (* src = "byte_striping_struct.v:27" *) byteStripingIN[2] : stripedLane0[2];
  assign _024_[3] = lane0VLD ? (* src = "byte_striping_struct.v:27" *) byteStripingIN[3] : stripedLane0[3];
  assign _024_[4] = lane0VLD ? (* src = "byte_striping_struct.v:27" *) byteStripingIN[4] : stripedLane0[4];
  assign _024_[5] = lane0VLD ? (* src = "byte_striping_struct.v:27" *) byteStripingIN[5] : stripedLane0[5];
  assign _024_[6] = lane0VLD ? (* src = "byte_striping_struct.v:27" *) byteStripingIN[6] : stripedLane0[6];
  assign _024_[7] = lane0VLD ? (* src = "byte_striping_struct.v:27" *) byteStripingIN[7] : stripedLane0[7];
  assign _002_[0] = _009_ ? (* src = "byte_striping_struct.v:26" *) stripedLane0[0] : _024_[0];
  assign _002_[1] = _009_ ? (* src = "byte_striping_struct.v:26" *) stripedLane0[1] : _024_[1];
  assign _002_[2] = _009_ ? (* src = "byte_striping_struct.v:26" *) stripedLane0[2] : _024_[2];
  assign _002_[3] = _009_ ? (* src = "byte_striping_struct.v:26" *) stripedLane0[3] : _024_[3];
  assign _002_[4] = _009_ ? (* src = "byte_striping_struct.v:26" *) stripedLane0[4] : _024_[4];
  assign _002_[5] = _009_ ? (* src = "byte_striping_struct.v:26" *) stripedLane0[5] : _024_[5];
  assign _002_[6] = _009_ ? (* src = "byte_striping_struct.v:26" *) stripedLane0[6] : _024_[6];
  assign _002_[7] = _009_ ? (* src = "byte_striping_struct.v:26" *) stripedLane0[7] : _024_[7];
  assign _000_ = _028_ ? (* src = "byte_striping_struct.v:26|<techmap.v>:445" *) _027_ : byteStripingVLD;
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane0[0] <= _002_[0];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane0[1] <= _002_[1];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane0[2] <= _002_[2];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane0[3] <= _002_[3];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane0[4] <= _002_[4];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane0[5] <= _002_[5];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane0[6] <= _002_[6];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane0[7] <= _002_[7];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane1[0] <= _003_[0];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane1[1] <= _003_[1];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane1[2] <= _003_[2];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane1[3] <= _003_[3];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane1[4] <= _003_[4];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane1[5] <= _003_[5];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane1[6] <= _003_[6];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane1[7] <= _003_[7];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane2[0] <= _004_[0];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane2[1] <= _004_[1];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane2[2] <= _004_[2];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane2[3] <= _004_[3];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane2[4] <= _004_[4];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane2[5] <= _004_[5];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane2[6] <= _004_[6];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane2[7] <= _004_[7];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane3[0] <= _005_[0];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane3[1] <= _005_[1];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane3[2] <= _005_[2];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane3[3] <= _005_[3];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane3[4] <= _005_[4];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane3[5] <= _005_[5];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane3[6] <= _005_[6];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      stripedLane3[7] <= _005_[7];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      byteStripingVLD <= _000_;
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      counter[0] <= _001_[0];
  (* src = "byte_striping_struct.v:19" *)
  always @(posedge clk1Mhz)
      counter[1] <= _001_[1];
  assign _010_[1] = counter[1] ^(* src = "byte_striping_struct.v:26" *)  1'b1;
  assign _026_[3] = _019_ &(* src = "byte_striping_struct.v:26|<techmap.v>:434" *)  _020_;
  assign _026_[2] = _017_ &(* src = "byte_striping_struct.v:26|<techmap.v>:434" *)  _018_;
  assign _026_[1] = _015_ &(* src = "byte_striping_struct.v:26|<techmap.v>:434" *)  _016_;
  assign _026_[0] = _025_ &(* src = "byte_striping_struct.v:26|<techmap.v>:434" *)  _014_;
  assign _006_[0] = counter[0] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _006_[1] = counter[1] ^(* src = "<techmap.v>:263" *)  counter[0];
endmodule
