/* Generated by Yosys 0.7+560 (git sha1 d9a2b430, gcc 7.3.1 -fPIC -Os) */

module fsm_synth(CLK, sReset, sInit, sEmpty, sFull, sPause, sContinue, oInit, oIdle, oError, stbPause, stbContinue, State, nState);
  wire [3:0] _000_;
  wire [3:0] _001_;
  wire _002_;
  wire _003_;
  wire [3:0] _004_;
  wire [7:0] _005_;
  wire [3:0] _006_;
  wire [3:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  input CLK;
  output [7:0] State;
  reg [3:0] continuar;
  output [7:0] nState;
  wire [7:0] nextState;
  output [3:0] oError;
  reg [3:0] oError;
  output oIdle;
  reg oIdle;
  output oInit;
  reg oInit;
  reg [3:0] pausa;
  input [3:0] sContinue;
  input [3:0] sEmpty;
  input [3:0] sFull;
  input sInit;
  input [3:0] sPause;
  input sReset;
  wire [7:0] state;
  output [3:0] stbContinue;
  reg [3:0] stbContinue;
  output [3:0] stbPause;
  reg [3:0] stbPause;
  NOR _140_ (
    .A(_031_),
    .B(_034_),
    .Y(_036_)
  );
  NAND _141_ (
    .A(_023_),
    .B(_035_),
    .Y(_037_)
  );
  NOR _142_ (
    .A(_029_),
    .B(_036_),
    .Y(_038_)
  );
  NAND _143_ (
    .A(_030_),
    .B(_037_),
    .Y(_039_)
  );
  NOR _144_ (
    .A(_020_),
    .B(_038_),
    .Y(nState[4])
  );
  NAND _145_ (
    .A(state[6]),
    .B(_026_),
    .Y(_040_)
  );
  NOR _146_ (
    .A(_024_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _147_ (
    .A(sReset),
    .B(_041_),
    .Y(_042_)
  );
  NOR _148_ (
    .A(sFull[3]),
    .B(sFull[2]),
    .Y(_043_)
  );
  NOR _149_ (
    .A(sFull[1]),
    .B(sFull[0]),
    .Y(_044_)
  );
  NAND _150_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _151_ (
    .A(sContinue[1]),
    .B(continuar[1]),
    .Y(_046_)
  );
  NOR _152_ (
    .A(sContinue[1]),
    .B(continuar[1]),
    .Y(_047_)
  );
  NOT _153_ (
    .A(_047_),
    .Y(_048_)
  );
  NAND _154_ (
    .A(_046_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _155_ (
    .A(_117_),
    .B(continuar[0]),
    .Y(_050_)
  );
  NOR _156_ (
    .A(sContinue[0]),
    .B(_131_),
    .Y(_051_)
  );
  NOR _157_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _158_ (
    .A(_049_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _159_ (
    .A(_115_),
    .B(continuar[3]),
    .Y(_054_)
  );
  NOR _160_ (
    .A(sContinue[3]),
    .B(_133_),
    .Y(_055_)
  );
  NOR _161_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _162_ (
    .A(_116_),
    .B(continuar[2]),
    .Y(_057_)
  );
  NOR _163_ (
    .A(sContinue[2]),
    .B(_132_),
    .Y(_058_)
  );
  NOR _164_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _165_ (
    .A(_056_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _166_ (
    .A(_053_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _167_ (
    .A(sContinue[1]),
    .B(sContinue[0]),
    .Y(_062_)
  );
  NAND _168_ (
    .A(_116_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _169_ (
    .A(sContinue[3]),
    .B(_063_),
    .Y(_064_)
  );
  NOR _170_ (
    .A(_061_),
    .B(_064_),
    .Y(_065_)
  );
  NOT _171_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR _172_ (
    .A(_021_),
    .B(_038_),
    .Y(_067_)
  );
  NAND _173_ (
    .A(_020_),
    .B(_039_),
    .Y(_068_)
  );
  NOR _174_ (
    .A(_065_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _175_ (
    .A(_066_),
    .B(_067_),
    .Y(_070_)
  );
  NAND _176_ (
    .A(_045_),
    .B(_069_),
    .Y(_071_)
  );
  NAND _177_ (
    .A(_042_),
    .B(_071_),
    .Y(nState[6])
  );
  NAND _178_ (
    .A(_065_),
    .B(_067_),
    .Y(_072_)
  );
  NOT _179_ (
    .A(_072_),
    .Y(nState[5])
  );
  NOR _180_ (
    .A(_122_),
    .B(state[1]),
    .Y(_073_)
  );
  NAND _181_ (
    .A(_022_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _182_ (
    .A(_032_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _183_ (
    .A(_041_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _184_ (
    .A(sReset),
    .B(_076_),
    .Y(nState[0])
  );
  NAND _185_ (
    .A(sReset),
    .B(_075_),
    .Y(_077_)
  );
  NAND _186_ (
    .A(_122_),
    .B(state[1]),
    .Y(_078_)
  );
  NAND _187_ (
    .A(_022_),
    .B(_033_),
    .Y(_079_)
  );
  NOR _188_ (
    .A(_078_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _189_ (
    .A(_126_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _190_ (
    .A(state[2]),
    .B(_124_),
    .Y(_082_)
  );
  NOR _191_ (
    .A(_034_),
    .B(_082_),
    .Y(_083_)
  );
  NOT _192_ (
    .A(_083_),
    .Y(_084_)
  );
  NAND _193_ (
    .A(_038_),
    .B(_076_),
    .Y(_085_)
  );
  NOR _194_ (
    .A(_083_),
    .B(_085_),
    .Y(_086_)
  );
  NAND _195_ (
    .A(_081_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _196_ (
    .A(_077_),
    .B(_087_),
    .Y(nState[1])
  );
  NAND _197_ (
    .A(sEmpty[3]),
    .B(sEmpty[2]),
    .Y(_088_)
  );
  NOT _198_ (
    .A(_088_),
    .Y(_089_)
  );
  NAND _199_ (
    .A(sEmpty[1]),
    .B(sEmpty[0]),
    .Y(_090_)
  );
  NOT _200_ (
    .A(_090_),
    .Y(_091_)
  );
  NOR _201_ (
    .A(_088_),
    .B(_090_),
    .Y(_092_)
  );
  NAND _202_ (
    .A(_089_),
    .B(_091_),
    .Y(_093_)
  );
  NOR _203_ (
    .A(_084_),
    .B(_092_),
    .Y(_094_)
  );
  NOR _204_ (
    .A(_045_),
    .B(_070_),
    .Y(_095_)
  );
  NOR _205_ (
    .A(_094_),
    .B(_095_),
    .Y(_096_)
  );
  NOT _206_ (
    .A(_096_),
    .Y(nState[3])
  );
  NAND _207_ (
    .A(_083_),
    .B(_092_),
    .Y(_097_)
  );
  NAND _208_ (
    .A(_081_),
    .B(_097_),
    .Y(nState[2])
  );
  NAND _209_ (
    .A(sContinue[0]),
    .B(sReset),
    .Y(_098_)
  );
  NOT _210_ (
    .A(_098_),
    .Y(_000_[0])
  );
  NAND _211_ (
    .A(sContinue[1]),
    .B(sReset),
    .Y(_099_)
  );
  NOT _212_ (
    .A(_099_),
    .Y(_000_[1])
  );
  NAND _213_ (
    .A(sContinue[2]),
    .B(sReset),
    .Y(_100_)
  );
  NOT _214_ (
    .A(_100_),
    .Y(_000_[2])
  );
  NAND _215_ (
    .A(sContinue[3]),
    .B(sReset),
    .Y(_101_)
  );
  NOT _216_ (
    .A(_101_),
    .Y(_000_[3])
  );
  NAND _217_ (
    .A(sPause[0]),
    .B(sReset),
    .Y(_102_)
  );
  NOT _218_ (
    .A(_102_),
    .Y(_004_[0])
  );
  NAND _219_ (
    .A(sPause[1]),
    .B(sReset),
    .Y(_103_)
  );
  NOT _220_ (
    .A(_103_),
    .Y(_004_[1])
  );
  NAND _221_ (
    .A(sPause[2]),
    .B(sReset),
    .Y(_104_)
  );
  NOT _222_ (
    .A(_104_),
    .Y(_004_[2])
  );
  NAND _223_ (
    .A(sPause[3]),
    .B(sReset),
    .Y(_105_)
  );
  NOT _224_ (
    .A(_105_),
    .Y(_004_[3])
  );
  NAND _225_ (
    .A(sReset),
    .B(nState[5]),
    .Y(_106_)
  );
  NOT _226_ (
    .A(_106_),
    .Y(_005_[5])
  );
  NOR _227_ (
    .A(_117_),
    .B(_106_),
    .Y(_006_[0])
  );
  NOR _228_ (
    .A(_072_),
    .B(_099_),
    .Y(_006_[1])
  );
  NOR _229_ (
    .A(_072_),
    .B(_100_),
    .Y(_006_[2])
  );
  NOR _230_ (
    .A(_115_),
    .B(_106_),
    .Y(_006_[3])
  );
  NAND _231_ (
    .A(sReset),
    .B(nState[4]),
    .Y(_107_)
  );
  NOT _232_ (
    .A(_107_),
    .Y(_005_[4])
  );
  NOR _233_ (
    .A(_114_),
    .B(_107_),
    .Y(_007_[0])
  );
  NOR _234_ (
    .A(_113_),
    .B(_107_),
    .Y(_007_[1])
  );
  NOR _235_ (
    .A(_112_),
    .B(_107_),
    .Y(_007_[2])
  );
  NOR _236_ (
    .A(_111_),
    .B(_107_),
    .Y(_007_[3])
  );
  NAND _237_ (
    .A(sReset),
    .B(nState[6]),
    .Y(_108_)
  );
  NOT _238_ (
    .A(_108_),
    .Y(_005_[6])
  );
  NOR _239_ (
    .A(_121_),
    .B(_108_),
    .Y(_001_[0])
  );
  NOR _240_ (
    .A(_120_),
    .B(_108_),
    .Y(_001_[1])
  );
  NOR _241_ (
    .A(_119_),
    .B(_108_),
    .Y(_001_[2])
  );
  NOR _242_ (
    .A(_118_),
    .B(_108_),
    .Y(_001_[3])
  );
  NAND _243_ (
    .A(sReset),
    .B(nState[2]),
    .Y(_109_)
  );
  NOT _244_ (
    .A(_109_),
    .Y(_005_[2])
  );
  NOR _245_ (
    .A(_093_),
    .B(_109_),
    .Y(_002_)
  );
  NAND _246_ (
    .A(sReset),
    .B(nState[1]),
    .Y(_110_)
  );
  NOT _247_ (
    .A(_110_),
    .Y(_005_[1])
  );
  NOR _248_ (
    .A(_126_),
    .B(_110_),
    .Y(_003_)
  );
  NOR _249_ (
    .A(_005_[0]),
    .B(_096_),
    .Y(_005_[3])
  );
  NOT _250_ (
    .A(sPause[3]),
    .Y(_111_)
  );
  NOT _251_ (
    .A(sPause[2]),
    .Y(_112_)
  );
  NOT _252_ (
    .A(sPause[1]),
    .Y(_113_)
  );
  NOT _253_ (
    .A(sPause[0]),
    .Y(_114_)
  );
  NOT _254_ (
    .A(sContinue[3]),
    .Y(_115_)
  );
  NOT _255_ (
    .A(sContinue[2]),
    .Y(_116_)
  );
  NOT _256_ (
    .A(sContinue[0]),
    .Y(_117_)
  );
  NOT _257_ (
    .A(sFull[3]),
    .Y(_118_)
  );
  NOT _258_ (
    .A(sFull[2]),
    .Y(_119_)
  );
  NOT _259_ (
    .A(sFull[1]),
    .Y(_120_)
  );
  NOT _260_ (
    .A(sFull[0]),
    .Y(_121_)
  );
  NOT _261_ (
    .A(state[0]),
    .Y(_122_)
  );
  NOT _262_ (
    .A(state[2]),
    .Y(_123_)
  );
  NOT _263_ (
    .A(state[3]),
    .Y(_124_)
  );
  NOT _264_ (
    .A(state[6]),
    .Y(_125_)
  );
  NOT _265_ (
    .A(sReset),
    .Y(_005_[0])
  );
  NOT _266_ (
    .A(sInit),
    .Y(_126_)
  );
  NOT _267_ (
    .A(pausa[0]),
    .Y(_127_)
  );
  NOT _268_ (
    .A(pausa[1]),
    .Y(_128_)
  );
  NOT _269_ (
    .A(pausa[2]),
    .Y(_129_)
  );
  NOT _270_ (
    .A(pausa[3]),
    .Y(_130_)
  );
  NOT _271_ (
    .A(continuar[0]),
    .Y(_131_)
  );
  NOT _272_ (
    .A(continuar[2]),
    .Y(_132_)
  );
  NOT _273_ (
    .A(continuar[3]),
    .Y(_133_)
  );
  NAND _274_ (
    .A(sPause[1]),
    .B(_128_),
    .Y(_134_)
  );
  NAND _275_ (
    .A(_113_),
    .B(pausa[1]),
    .Y(_135_)
  );
  NAND _276_ (
    .A(_134_),
    .B(_135_),
    .Y(_136_)
  );
  NAND _277_ (
    .A(sPause[0]),
    .B(_127_),
    .Y(_137_)
  );
  NAND _278_ (
    .A(_114_),
    .B(pausa[0]),
    .Y(_138_)
  );
  NAND _279_ (
    .A(_137_),
    .B(_138_),
    .Y(_139_)
  );
  NOR _280_ (
    .A(_136_),
    .B(_139_),
    .Y(_008_)
  );
  NAND _281_ (
    .A(sPause[3]),
    .B(_130_),
    .Y(_009_)
  );
  NAND _282_ (
    .A(_111_),
    .B(pausa[3]),
    .Y(_010_)
  );
  NAND _283_ (
    .A(_009_),
    .B(_010_),
    .Y(_011_)
  );
  NAND _284_ (
    .A(sPause[2]),
    .B(_129_),
    .Y(_012_)
  );
  NAND _285_ (
    .A(_112_),
    .B(pausa[2]),
    .Y(_013_)
  );
  NAND _286_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _287_ (
    .A(_011_),
    .B(_014_),
    .Y(_015_)
  );
  NAND _288_ (
    .A(_008_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _289_ (
    .A(sPause[1]),
    .B(sPause[0]),
    .Y(_017_)
  );
  NOR _290_ (
    .A(sPause[3]),
    .B(sPause[2]),
    .Y(_018_)
  );
  NAND _291_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _292_ (
    .A(_016_),
    .B(_019_),
    .Y(_020_)
  );
  NOT _293_ (
    .A(_020_),
    .Y(_021_)
  );
  NOR _294_ (
    .A(state[2]),
    .B(state[3]),
    .Y(_022_)
  );
  NOR _295_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_023_)
  );
  NAND _296_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  NAND _297_ (
    .A(state[4]),
    .B(state[5]),
    .Y(_025_)
  );
  NOR _298_ (
    .A(state[4]),
    .B(state[5]),
    .Y(_026_)
  );
  NOR _299_ (
    .A(state[6]),
    .B(_026_),
    .Y(_027_)
  );
  NAND _300_ (
    .A(_025_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _301_ (
    .A(_024_),
    .B(_028_),
    .Y(_029_)
  );
  NOT _302_ (
    .A(_029_),
    .Y(_030_)
  );
  NAND _303_ (
    .A(_123_),
    .B(state[3]),
    .Y(_031_)
  );
  NAND _304_ (
    .A(_125_),
    .B(_026_),
    .Y(_032_)
  );
  NOT _305_ (
    .A(_032_),
    .Y(_033_)
  );
  NAND _306_ (
    .A(_023_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _307_ (
    .A(_031_),
    .B(_032_),
    .Y(_035_)
  );
  always @(posedge CLK)
      oInit <= _003_;
  always @(posedge CLK)
      oIdle <= _002_;
  always @(posedge CLK)
      oError[0] <= _001_[0];
  always @(posedge CLK)
      oError[1] <= _001_[1];
  always @(posedge CLK)
      oError[2] <= _001_[2];
  always @(posedge CLK)
      oError[3] <= _001_[3];
  always @(posedge CLK)
      stbPause[0] <= _007_[0];
  always @(posedge CLK)
      stbPause[1] <= _007_[1];
  always @(posedge CLK)
      stbPause[2] <= _007_[2];
  always @(posedge CLK)
      stbPause[3] <= _007_[3];
  always @(posedge CLK)
      stbContinue[0] <= _006_[0];
  always @(posedge CLK)
      stbContinue[1] <= _006_[1];
  always @(posedge CLK)
      stbContinue[2] <= _006_[2];
  always @(posedge CLK)
      stbContinue[3] <= _006_[3];
  always @(posedge CLK)
      pausa[0] <= _004_[0];
  always @(posedge CLK)
      pausa[1] <= _004_[1];
  always @(posedge CLK)
      pausa[2] <= _004_[2];
  always @(posedge CLK)
      pausa[3] <= _004_[3];
  always @(posedge CLK)
      continuar[0] <= _000_[0];
  always @(posedge CLK)
      continuar[1] <= _000_[1];
  always @(posedge CLK)
      continuar[2] <= _000_[2];
  always @(posedge CLK)
      continuar[3] <= _000_[3];
  reg \state_reg[0] ;
  always @(posedge CLK)
      \state_reg[0]  <= _005_[0];
  assign state[0] = \state_reg[0] ;
  reg \state_reg[1] ;
  always @(posedge CLK)
      \state_reg[1]  <= _005_[1];
  assign state[1] = \state_reg[1] ;
  reg \state_reg[2] ;
  always @(posedge CLK)
      \state_reg[2]  <= _005_[2];
  assign state[2] = \state_reg[2] ;
  reg \state_reg[3] ;
  always @(posedge CLK)
      \state_reg[3]  <= _005_[3];
  assign state[3] = \state_reg[3] ;
  reg \state_reg[4] ;
  always @(posedge CLK)
      \state_reg[4]  <= _005_[4];
  assign state[4] = \state_reg[4] ;
  reg \state_reg[5] ;
  always @(posedge CLK)
      \state_reg[5]  <= _005_[5];
  assign state[5] = \state_reg[5] ;
  reg \state_reg[6] ;
  always @(posedge CLK)
      \state_reg[6]  <= _005_[6];
  assign state[6] = \state_reg[6] ;
  assign State = { 1'h0, state[6:0] };
  assign nState[7] = 1'h0;
  assign nextState = { 1'h0, nState[6:0] };
  assign state[7] = 1'h0;
endmodule
