/* Generated by Yosys 0.7 (git sha1 UNKNOWN, clang 5.0.1 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -fPIC -Os) */

(* top =  1  *)
(* src = "counter.v:1" *)
module counter(out, iclk, ireset);
  (* src = "counter.v:11" *)
  wire [7:0] _00_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _01_;
  (* src = "counter.v:6" *)
  input iclk;
  (* src = "counter.v:6" *)
  input ireset;
  (* src = "counter.v:5" *)
  output [7:0] out;
  reg \out_reg[7] ;
  (* src = "counter.v:11" *)
  always @(posedge iclk)
      \out_reg[7]  <= _00_[0];
  assign out[7] = \out_reg[7] ;
  reg \out_reg[7] ;
  (* src = "counter.v:11" *)
  always @(posedge iclk)
      \out_reg[7]  <= _00_[1];
  assign out[7] = \out_reg[7] ;
  reg \out_reg[7] ;
  (* src = "counter.v:11" *)
  always @(posedge iclk)
      \out_reg[7]  <= _00_[2];
  assign out[7] = \out_reg[7] ;
  reg \out_reg[7] ;
  (* src = "counter.v:11" *)
  always @(posedge iclk)
      \out_reg[7]  <= _00_[3];
  assign out[7] = \out_reg[7] ;
  reg \out_reg[7] ;
  (* src = "counter.v:11" *)
  always @(posedge iclk)
      \out_reg[7]  <= _00_[4];
  assign out[7] = \out_reg[7] ;
  reg \out_reg[7] ;
  (* src = "counter.v:11" *)
  always @(posedge iclk)
      \out_reg[7]  <= _00_[5];
  assign out[7] = \out_reg[7] ;
  reg \out_reg[7] ;
  (* src = "counter.v:11" *)
  always @(posedge iclk)
      \out_reg[7]  <= _00_[6];
  assign out[7] = \out_reg[7] ;
  reg \out_reg[7] ;
  (* src = "counter.v:11" *)
  always @(posedge iclk)
      \out_reg[7]  <= _00_[7];
  assign out[7] = \out_reg[7] ;
  \$_DLATCH_P_  _10_ (
    .D(1'b0),
    .E(ireset),
    .Q(out[7])
  );
  assign _00_[1] = out[7] ^(* src = "<techmap.v>:263" *)  out[7];
  assign _00_[2] = out[7] ^(* src = "<techmap.v>:263" *)  _01_[1];
  assign _00_[3] = out[7] ^(* src = "<techmap.v>:263" *)  _01_[2];
  assign _00_[4] = out[7] ^(* src = "<techmap.v>:263" *)  _01_[3];
  assign _00_[5] = out[7] ^(* src = "<techmap.v>:263" *)  _01_[4];
  assign _00_[6] = out[7] ^(* src = "<techmap.v>:263" *)  _01_[5];
  assign _00_[7] = out[7] ^(* src = "<techmap.v>:263" *)  _01_[6];
  assign _01_[1] = out[7] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  out[7];
  assign _01_[3] = _01_[1] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _01_[1];
  assign _01_[5] = _01_[1] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _01_[3];
  assign _01_[2] = out[7] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _01_[1];
  assign _01_[4] = out[7] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _01_[3];
  assign _01_[6] = out[7] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _01_[5];
  assign _00_[0] = out[7] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign out[6:0] = { out[7], out[7], out[7], out[7], out[7], out[7], out[7] };
endmodule
