`include "cmos_cells.v"
/* Generated by Yosys 0.7 (git sha1 UNKNOWN, clang 5.0.1 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -fPIC -Os) */

module byte_joining_synth(Lane_0, Lane_1, Lane_2, Lane_3, ctr_3, clk250k, out);
  reg [7:0] L0;
  reg [7:0] L1;
  reg [7:0] L2;
  reg [7:0] L3;
  input [7:0] Lane_0;
  input [7:0] Lane_1;
  input [7:0] Lane_2;
  input [7:0] Lane_3;
  input clk250k;
  input [1:0] ctr_3;
  output [7:0] out;
  always @(posedge clk250k)
      L0[0] <= Lane_0[0];
  always @(posedge clk250k)
      L0[1] <= Lane_0[1];
  always @(posedge clk250k)
      L0[2] <= Lane_0[2];
  always @(posedge clk250k)
      L0[3] <= Lane_0[3];
  always @(posedge clk250k)
      L0[4] <= Lane_0[4];
  always @(posedge clk250k)
      L0[5] <= Lane_0[5];
  always @(posedge clk250k)
      L0[6] <= Lane_0[6];
  always @(posedge clk250k)
      L0[7] <= Lane_0[7];
  always @(posedge clk250k)
      L1[0] <= Lane_1[0];
  always @(posedge clk250k)
      L1[1] <= Lane_1[1];
  always @(posedge clk250k)
      L1[2] <= Lane_1[2];
  always @(posedge clk250k)
      L1[3] <= Lane_1[3];
  always @(posedge clk250k)
      L1[4] <= Lane_1[4];
  always @(posedge clk250k)
      L1[5] <= Lane_1[5];
  always @(posedge clk250k)
      L1[6] <= Lane_1[6];
  always @(posedge clk250k)
      L1[7] <= Lane_1[7];
  always @(posedge clk250k)
      L2[0] <= Lane_2[0];
  always @(posedge clk250k)
      L2[1] <= Lane_2[1];
  always @(posedge clk250k)
      L2[2] <= Lane_2[2];
  always @(posedge clk250k)
      L2[3] <= Lane_2[3];
  always @(posedge clk250k)
      L2[4] <= Lane_2[4];
  always @(posedge clk250k)
      L2[5] <= Lane_2[5];
  always @(posedge clk250k)
      L2[6] <= Lane_2[6];
  always @(posedge clk250k)
      L2[7] <= Lane_2[7];
  always @(posedge clk250k)
      L3[0] <= Lane_3[0];
  always @(posedge clk250k)
      L3[1] <= Lane_3[1];
  always @(posedge clk250k)
      L3[2] <= Lane_3[2];
  always @(posedge clk250k)
      L3[3] <= Lane_3[3];
  always @(posedge clk250k)
      L3[4] <= Lane_3[4];
  always @(posedge clk250k)
      L3[5] <= Lane_3[5];
  always @(posedge clk250k)
      L3[6] <= Lane_3[6];
  always @(posedge clk250k)
      L3[7] <= Lane_3[7];
  mux4a1_synth mux_cond (
    .In0(L0),
    .In1(L1),
    .In2(L2),
    .In3(L3),
    .Sel(ctr_3),
    .outmux(out)
  );
endmodule

module byte_striping_synth(stripedLane0, stripedLane1, stripedLane2, stripedLane3, byteStripingVLD, byteStripingIN, laneVLD, clk250k, clk1Mhz, counter, reset);
  wire _000_;
  wire [1:0] _001_;
  wire [7:0] _002_;
  wire [7:0] _003_;
  wire [7:0] _004_;
  wire [7:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  input [7:0] byteStripingIN;
  output byteStripingVLD;
  reg byteStripingVLD;
  input clk1Mhz;
  input clk250k;
  output [1:0] counter;
  reg [1:0] counter;
  input laneVLD;
  input reset;
  output [7:0] stripedLane0;
  reg [7:0] stripedLane0;
  output [7:0] stripedLane1;
  reg [7:0] stripedLane1;
  output [7:0] stripedLane2;
  reg [7:0] stripedLane2;
  output [7:0] stripedLane3;
  reg [7:0] stripedLane3;
  NOT _104_ (
    .A(reset),
    .Y(_088_)
  );
  NOR _105_ (
    .A(_088_),
    .B(counter[0]),
    .Y(_001_[0])
  );
  NOT _106_ (
    .A(counter[0]),
    .Y(_089_)
  );
  NOT _107_ (
    .A(counter[1]),
    .Y(_090_)
  );
  NOR _108_ (
    .A(_090_),
    .B(_089_),
    .Y(_091_)
  );
  NAND _109_ (
    .A(_090_),
    .B(_089_),
    .Y(_092_)
  );
  NAND _110_ (
    .A(_092_),
    .B(reset),
    .Y(_093_)
  );
  NOR _111_ (
    .A(_093_),
    .B(_091_),
    .Y(_001_[1])
  );
  NAND _112_ (
    .A(_091_),
    .B(laneVLD),
    .Y(_094_)
  );
  NOR _113_ (
    .A(_094_),
    .B(byteStripingIN[0]),
    .Y(_095_)
  );
  NOT _114_ (
    .A(laneVLD),
    .Y(_096_)
  );
  NAND _115_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_097_)
  );
  NOR _116_ (
    .A(_097_),
    .B(_096_),
    .Y(_098_)
  );
  NOR _117_ (
    .A(_098_),
    .B(stripedLane3[0]),
    .Y(_099_)
  );
  NOR _118_ (
    .A(_099_),
    .B(_095_),
    .Y(_005_[0])
  );
  NAND _119_ (
    .A(_094_),
    .B(stripedLane3[1]),
    .Y(_100_)
  );
  NOT _120_ (
    .A(byteStripingIN[1]),
    .Y(_101_)
  );
  NOR _121_ (
    .A(_101_),
    .B(_096_),
    .Y(_102_)
  );
  NAND _122_ (
    .A(_102_),
    .B(_091_),
    .Y(_103_)
  );
  NAND _123_ (
    .A(_103_),
    .B(_100_),
    .Y(_005_[1])
  );
  NAND _124_ (
    .A(_094_),
    .B(stripedLane3[2]),
    .Y(_006_)
  );
  NOT _125_ (
    .A(byteStripingIN[2]),
    .Y(_007_)
  );
  NOR _126_ (
    .A(_007_),
    .B(_096_),
    .Y(_008_)
  );
  NAND _127_ (
    .A(_008_),
    .B(_091_),
    .Y(_009_)
  );
  NAND _128_ (
    .A(_009_),
    .B(_006_),
    .Y(_005_[2])
  );
  NAND _129_ (
    .A(_094_),
    .B(stripedLane3[3]),
    .Y(_010_)
  );
  NOT _130_ (
    .A(byteStripingIN[3]),
    .Y(_011_)
  );
  NOR _131_ (
    .A(_011_),
    .B(_096_),
    .Y(_012_)
  );
  NAND _132_ (
    .A(_012_),
    .B(_091_),
    .Y(_013_)
  );
  NAND _133_ (
    .A(_013_),
    .B(_010_),
    .Y(_005_[3])
  );
  NAND _134_ (
    .A(_094_),
    .B(stripedLane3[4]),
    .Y(_014_)
  );
  NOT _135_ (
    .A(byteStripingIN[4]),
    .Y(_015_)
  );
  NOR _136_ (
    .A(_015_),
    .B(_096_),
    .Y(_016_)
  );
  NAND _137_ (
    .A(_016_),
    .B(_091_),
    .Y(_017_)
  );
  NAND _138_ (
    .A(_017_),
    .B(_014_),
    .Y(_005_[4])
  );
  NAND _139_ (
    .A(_094_),
    .B(stripedLane3[5]),
    .Y(_018_)
  );
  NOT _140_ (
    .A(byteStripingIN[5]),
    .Y(_019_)
  );
  NOR _141_ (
    .A(_019_),
    .B(_096_),
    .Y(_020_)
  );
  NAND _142_ (
    .A(_020_),
    .B(_091_),
    .Y(_021_)
  );
  NAND _143_ (
    .A(_021_),
    .B(_018_),
    .Y(_005_[5])
  );
  NAND _144_ (
    .A(_094_),
    .B(stripedLane3[6]),
    .Y(_022_)
  );
  NOT _145_ (
    .A(byteStripingIN[6]),
    .Y(_023_)
  );
  NOR _146_ (
    .A(_023_),
    .B(_096_),
    .Y(_024_)
  );
  NAND _147_ (
    .A(_024_),
    .B(_091_),
    .Y(_025_)
  );
  NAND _148_ (
    .A(_025_),
    .B(_022_),
    .Y(_005_[6])
  );
  NAND _149_ (
    .A(_094_),
    .B(stripedLane3[7]),
    .Y(_026_)
  );
  NOT _150_ (
    .A(byteStripingIN[7]),
    .Y(_027_)
  );
  NOR _151_ (
    .A(_027_),
    .B(_096_),
    .Y(_028_)
  );
  NAND _152_ (
    .A(_028_),
    .B(_091_),
    .Y(_029_)
  );
  NAND _153_ (
    .A(_029_),
    .B(_026_),
    .Y(_005_[7])
  );
  NOR _154_ (
    .A(_090_),
    .B(counter[0]),
    .Y(_030_)
  );
  NAND _155_ (
    .A(_030_),
    .B(laneVLD),
    .Y(_031_)
  );
  NAND _156_ (
    .A(_031_),
    .B(stripedLane2[0]),
    .Y(_032_)
  );
  NOT _157_ (
    .A(byteStripingIN[0]),
    .Y(_033_)
  );
  NOR _158_ (
    .A(_033_),
    .B(_096_),
    .Y(_034_)
  );
  NAND _159_ (
    .A(_034_),
    .B(_030_),
    .Y(_035_)
  );
  NAND _160_ (
    .A(_035_),
    .B(_032_),
    .Y(_004_[0])
  );
  NAND _161_ (
    .A(_031_),
    .B(stripedLane2[1]),
    .Y(_036_)
  );
  NAND _162_ (
    .A(_030_),
    .B(_102_),
    .Y(_037_)
  );
  NAND _163_ (
    .A(_037_),
    .B(_036_),
    .Y(_004_[1])
  );
  NAND _164_ (
    .A(_031_),
    .B(stripedLane2[2]),
    .Y(_038_)
  );
  NAND _165_ (
    .A(_030_),
    .B(_008_),
    .Y(_039_)
  );
  NAND _166_ (
    .A(_039_),
    .B(_038_),
    .Y(_004_[2])
  );
  NAND _167_ (
    .A(_031_),
    .B(stripedLane2[3]),
    .Y(_040_)
  );
  NAND _168_ (
    .A(_030_),
    .B(_012_),
    .Y(_041_)
  );
  NAND _169_ (
    .A(_041_),
    .B(_040_),
    .Y(_004_[3])
  );
  NAND _170_ (
    .A(_031_),
    .B(stripedLane2[4]),
    .Y(_042_)
  );
  NAND _171_ (
    .A(_030_),
    .B(_016_),
    .Y(_043_)
  );
  NAND _172_ (
    .A(_043_),
    .B(_042_),
    .Y(_004_[4])
  );
  NAND _173_ (
    .A(_031_),
    .B(stripedLane2[5]),
    .Y(_044_)
  );
  NAND _174_ (
    .A(_030_),
    .B(_020_),
    .Y(_045_)
  );
  NAND _175_ (
    .A(_045_),
    .B(_044_),
    .Y(_004_[5])
  );
  NAND _176_ (
    .A(_031_),
    .B(stripedLane2[6]),
    .Y(_046_)
  );
  NAND _177_ (
    .A(_030_),
    .B(_024_),
    .Y(_047_)
  );
  NAND _178_ (
    .A(_047_),
    .B(_046_),
    .Y(_004_[6])
  );
  NAND _179_ (
    .A(_031_),
    .B(stripedLane2[7]),
    .Y(_048_)
  );
  NAND _180_ (
    .A(_030_),
    .B(_028_),
    .Y(_049_)
  );
  NAND _181_ (
    .A(_049_),
    .B(_048_),
    .Y(_004_[7])
  );
  NOR _182_ (
    .A(counter[1]),
    .B(_089_),
    .Y(_050_)
  );
  NAND _183_ (
    .A(_050_),
    .B(laneVLD),
    .Y(_051_)
  );
  NAND _184_ (
    .A(_051_),
    .B(stripedLane1[0]),
    .Y(_052_)
  );
  NAND _185_ (
    .A(_050_),
    .B(_034_),
    .Y(_053_)
  );
  NAND _186_ (
    .A(_053_),
    .B(_052_),
    .Y(_003_[0])
  );
  NAND _187_ (
    .A(_051_),
    .B(stripedLane1[1]),
    .Y(_054_)
  );
  NAND _188_ (
    .A(_050_),
    .B(_102_),
    .Y(_055_)
  );
  NAND _189_ (
    .A(_055_),
    .B(_054_),
    .Y(_003_[1])
  );
  NAND _190_ (
    .A(_051_),
    .B(stripedLane1[2]),
    .Y(_056_)
  );
  NAND _191_ (
    .A(_050_),
    .B(_008_),
    .Y(_057_)
  );
  NAND _192_ (
    .A(_057_),
    .B(_056_),
    .Y(_003_[2])
  );
  NAND _193_ (
    .A(_051_),
    .B(stripedLane1[3]),
    .Y(_058_)
  );
  NAND _194_ (
    .A(_050_),
    .B(_012_),
    .Y(_059_)
  );
  NAND _195_ (
    .A(_059_),
    .B(_058_),
    .Y(_003_[3])
  );
  NAND _196_ (
    .A(_051_),
    .B(stripedLane1[4]),
    .Y(_060_)
  );
  NAND _197_ (
    .A(_050_),
    .B(_016_),
    .Y(_061_)
  );
  NAND _198_ (
    .A(_061_),
    .B(_060_),
    .Y(_003_[4])
  );
  NAND _199_ (
    .A(_051_),
    .B(stripedLane1[5]),
    .Y(_062_)
  );
  NAND _200_ (
    .A(_050_),
    .B(_020_),
    .Y(_063_)
  );
  NAND _201_ (
    .A(_063_),
    .B(_062_),
    .Y(_003_[5])
  );
  NAND _202_ (
    .A(_051_),
    .B(stripedLane1[6]),
    .Y(_064_)
  );
  NAND _203_ (
    .A(_050_),
    .B(_024_),
    .Y(_065_)
  );
  NAND _204_ (
    .A(_065_),
    .B(_064_),
    .Y(_003_[6])
  );
  NAND _205_ (
    .A(_051_),
    .B(stripedLane1[7]),
    .Y(_066_)
  );
  NAND _206_ (
    .A(_050_),
    .B(_028_),
    .Y(_067_)
  );
  NAND _207_ (
    .A(_067_),
    .B(_066_),
    .Y(_003_[7])
  );
  NOR _208_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_068_)
  );
  NAND _209_ (
    .A(_068_),
    .B(laneVLD),
    .Y(_069_)
  );
  NOR _210_ (
    .A(_069_),
    .B(byteStripingIN[0]),
    .Y(_070_)
  );
  NOR _211_ (
    .A(_092_),
    .B(_096_),
    .Y(_071_)
  );
  NOR _212_ (
    .A(_071_),
    .B(stripedLane0[0]),
    .Y(_072_)
  );
  NOR _213_ (
    .A(_072_),
    .B(_070_),
    .Y(_002_[0])
  );
  NAND _214_ (
    .A(_069_),
    .B(stripedLane0[1]),
    .Y(_073_)
  );
  NAND _215_ (
    .A(_102_),
    .B(_068_),
    .Y(_074_)
  );
  NAND _216_ (
    .A(_074_),
    .B(_073_),
    .Y(_002_[1])
  );
  NAND _217_ (
    .A(_069_),
    .B(stripedLane0[2]),
    .Y(_075_)
  );
  NAND _218_ (
    .A(_008_),
    .B(_068_),
    .Y(_076_)
  );
  NAND _219_ (
    .A(_076_),
    .B(_075_),
    .Y(_002_[2])
  );
  NAND _220_ (
    .A(_069_),
    .B(stripedLane0[3]),
    .Y(_077_)
  );
  NAND _221_ (
    .A(_012_),
    .B(_068_),
    .Y(_078_)
  );
  NAND _222_ (
    .A(_078_),
    .B(_077_),
    .Y(_002_[3])
  );
  NAND _223_ (
    .A(_069_),
    .B(stripedLane0[4]),
    .Y(_079_)
  );
  NAND _224_ (
    .A(_016_),
    .B(_068_),
    .Y(_080_)
  );
  NAND _225_ (
    .A(_080_),
    .B(_079_),
    .Y(_002_[4])
  );
  NAND _226_ (
    .A(_069_),
    .B(stripedLane0[5]),
    .Y(_081_)
  );
  NAND _227_ (
    .A(_020_),
    .B(_068_),
    .Y(_082_)
  );
  NAND _228_ (
    .A(_082_),
    .B(_081_),
    .Y(_002_[5])
  );
  NAND _229_ (
    .A(_069_),
    .B(stripedLane0[6]),
    .Y(_083_)
  );
  NAND _230_ (
    .A(_024_),
    .B(_068_),
    .Y(_084_)
  );
  NAND _231_ (
    .A(_084_),
    .B(_083_),
    .Y(_002_[6])
  );
  NAND _232_ (
    .A(_069_),
    .B(stripedLane0[7]),
    .Y(_085_)
  );
  NAND _233_ (
    .A(_028_),
    .B(_068_),
    .Y(_086_)
  );
  NAND _234_ (
    .A(_086_),
    .B(_085_),
    .Y(_002_[7])
  );
  NAND _235_ (
    .A(_096_),
    .B(byteStripingVLD),
    .Y(_087_)
  );
  NAND _236_ (
    .A(_087_),
    .B(_094_),
    .Y(_000_)
  );
  always @(posedge clk1Mhz)
      stripedLane0[0] <= _002_[0];
  always @(posedge clk1Mhz)
      stripedLane0[1] <= _002_[1];
  always @(posedge clk1Mhz)
      stripedLane0[2] <= _002_[2];
  always @(posedge clk1Mhz)
      stripedLane0[3] <= _002_[3];
  always @(posedge clk1Mhz)
      stripedLane0[4] <= _002_[4];
  always @(posedge clk1Mhz)
      stripedLane0[5] <= _002_[5];
  always @(posedge clk1Mhz)
      stripedLane0[6] <= _002_[6];
  always @(posedge clk1Mhz)
      stripedLane0[7] <= _002_[7];
  always @(posedge clk1Mhz)
      stripedLane1[0] <= _003_[0];
  always @(posedge clk1Mhz)
      stripedLane1[1] <= _003_[1];
  always @(posedge clk1Mhz)
      stripedLane1[2] <= _003_[2];
  always @(posedge clk1Mhz)
      stripedLane1[3] <= _003_[3];
  always @(posedge clk1Mhz)
      stripedLane1[4] <= _003_[4];
  always @(posedge clk1Mhz)
      stripedLane1[5] <= _003_[5];
  always @(posedge clk1Mhz)
      stripedLane1[6] <= _003_[6];
  always @(posedge clk1Mhz)
      stripedLane1[7] <= _003_[7];
  always @(posedge clk1Mhz)
      stripedLane2[0] <= _004_[0];
  always @(posedge clk1Mhz)
      stripedLane2[1] <= _004_[1];
  always @(posedge clk1Mhz)
      stripedLane2[2] <= _004_[2];
  always @(posedge clk1Mhz)
      stripedLane2[3] <= _004_[3];
  always @(posedge clk1Mhz)
      stripedLane2[4] <= _004_[4];
  always @(posedge clk1Mhz)
      stripedLane2[5] <= _004_[5];
  always @(posedge clk1Mhz)
      stripedLane2[6] <= _004_[6];
  always @(posedge clk1Mhz)
      stripedLane2[7] <= _004_[7];
  always @(posedge clk1Mhz)
      stripedLane3[0] <= _005_[0];
  always @(posedge clk1Mhz)
      stripedLane3[1] <= _005_[1];
  always @(posedge clk1Mhz)
      stripedLane3[2] <= _005_[2];
  always @(posedge clk1Mhz)
      stripedLane3[3] <= _005_[3];
  always @(posedge clk1Mhz)
      stripedLane3[4] <= _005_[4];
  always @(posedge clk1Mhz)
      stripedLane3[5] <= _005_[5];
  always @(posedge clk1Mhz)
      stripedLane3[6] <= _005_[6];
  always @(posedge clk1Mhz)
      stripedLane3[7] <= _005_[7];
  always @(posedge clk1Mhz)
      byteStripingVLD <= _000_;
  always @(posedge clk1Mhz)
      counter[0] <= _001_[0];
  always @(posedge clk1Mhz)
      counter[1] <= _001_[1];
endmodule

module ctr3_synth(CLK, reset, CTR);
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input CLK;
  output [1:0] CTR;
  reg [1:0] CTR;
  input reset;
  NAND _05_ (
    .A(CTR[0]),
    .B(reset),
    .Y(_00_[0])
  );
  NOT _06_ (
    .A(CTR[1]),
    .Y(_02_)
  );
  NAND _07_ (
    .A(_02_),
    .B(CTR[0]),
    .Y(_03_)
  );
  NAND _08_ (
    .A(_02_),
    .B(reset),
    .Y(_04_)
  );
  NAND _09_ (
    .A(_04_),
    .B(_00_[0]),
    .Y(_01_)
  );
  NAND _10_ (
    .A(_01_),
    .B(_03_),
    .Y(_00_[1])
  );
  always @(posedge CLK)
      CTR[0] <= _00_[0];
  always @(posedge CLK)
      CTR[1] <= _00_[1];
endmodule

module ffd_p2s_synth(CLK, D, ENB, valid_in, Q, valid_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input CLK;
  input D;
  input ENB;
  output Q;
  reg Q;
  input valid_in;
  output valid_out;
  NOR _05_ (
    .A(valid_in),
    .B(Q),
    .Y(_01_)
  );
  NOT _06_ (
    .A(D),
    .Y(_02_)
  );
  NAND _07_ (
    .A(valid_in),
    .B(_02_),
    .Y(_03_)
  );
  NAND _08_ (
    .A(_03_),
    .B(ENB),
    .Y(_04_)
  );
  NOR _09_ (
    .A(_04_),
    .B(_01_),
    .Y(_00_)
  );
  always @(posedge CLK)
      Q <= _00_;
  assign valid_out = 1'b1;
endmodule

module ffd_s2p_synth(CLK, D, ENB, Q);
  wire _0_;
  wire _1_;
  wire _2_;
  input CLK;
  input D;
  input ENB;
  output Q;
  reg Q;
  NOT _3_ (
    .A(D),
    .Y(_1_)
  );
  NOT _4_ (
    .A(ENB),
    .Y(_2_)
  );
  NOR _5_ (
    .A(_2_),
    .B(_1_),
    .Y(_0_)
  );
  always @(posedge CLK)
      Q <= _0_;
endmodule

module freq_div_synth(CLK, reset, CLK_2, CLK_4, CLK_8);
  wire _0_;
  wire _1_;
  input CLK;
  output CLK_2;
  reg CLK_2;
  output CLK_4;
  output CLK_8;
  input reset;
  NOT _2_ (
    .A(reset),
    .Y(_1_)
  );
  NOR _3_ (
    .A(CLK_2),
    .B(_1_),
    .Y(_0_)
  );
  always @(posedge CLK)
      CLK_2 <= _0_;
  assign CLK_4 = 1'b0;
  assign CLK_8 = 1'b0;
endmodule

module multiplexer_synth(muxOUT, muxVLD, TLP, COM, PAD, SKP, STP, SDP, END, EDB, FTS, IDL, muxCTRL, muxCLK);
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  input [7:0] COM;
  input [7:0] EDB;
  input [7:0] END;
  input [7:0] FTS;
  input [7:0] IDL;
  input [7:0] PAD;
  input [7:0] SDP;
  input [7:0] SKP;
  input [7:0] STP;
  input [7:0] TLP;
  input muxCLK;
  input [3:0] muxCTRL;
  output [7:0] muxOUT;
  reg [7:0] muxOUT;
  output muxVLD;
  reg muxVLD;
  NOT _224_ (
    .A(muxCTRL[2]),
    .Y(_002_)
  );
  NOT _225_ (
    .A(muxCTRL[1]),
    .Y(_003_)
  );
  NAND _226_ (
    .A(_003_),
    .B(_002_),
    .Y(_004_)
  );
  NAND _227_ (
    .A(_004_),
    .B(muxCTRL[3]),
    .Y(_001_)
  );
  NOR _228_ (
    .A(_001_),
    .B(muxOUT[0]),
    .Y(_005_)
  );
  NOT _229_ (
    .A(muxCTRL[0]),
    .Y(_006_)
  );
  NAND _230_ (
    .A(_003_),
    .B(_006_),
    .Y(_007_)
  );
  NAND _231_ (
    .A(muxCTRL[3]),
    .B(_002_),
    .Y(_008_)
  );
  NOR _232_ (
    .A(_008_),
    .B(_007_),
    .Y(_009_)
  );
  NAND _233_ (
    .A(_009_),
    .B(FTS[0]),
    .Y(_010_)
  );
  NOT _234_ (
    .A(TLP[0]),
    .Y(_011_)
  );
  NOR _235_ (
    .A(muxCTRL[1]),
    .B(muxCTRL[0]),
    .Y(_012_)
  );
  NOR _236_ (
    .A(muxCTRL[3]),
    .B(muxCTRL[2]),
    .Y(_013_)
  );
  NAND _237_ (
    .A(_013_),
    .B(_012_),
    .Y(_014_)
  );
  NOR _238_ (
    .A(_014_),
    .B(_011_),
    .Y(_015_)
  );
  NOT _239_ (
    .A(SDP[0]),
    .Y(_016_)
  );
  NOR _240_ (
    .A(muxCTRL[3]),
    .B(_002_),
    .Y(_017_)
  );
  NOR _241_ (
    .A(muxCTRL[1]),
    .B(_006_),
    .Y(_018_)
  );
  NAND _242_ (
    .A(_018_),
    .B(_017_),
    .Y(_019_)
  );
  NOR _243_ (
    .A(_019_),
    .B(_016_),
    .Y(_020_)
  );
  NOR _244_ (
    .A(_020_),
    .B(_015_),
    .Y(_021_)
  );
  NAND _245_ (
    .A(_021_),
    .B(_010_),
    .Y(_022_)
  );
  NOT _246_ (
    .A(muxCTRL[3]),
    .Y(_023_)
  );
  NAND _247_ (
    .A(_023_),
    .B(muxCTRL[2]),
    .Y(_024_)
  );
  NOR _248_ (
    .A(_024_),
    .B(_007_),
    .Y(_025_)
  );
  NAND _249_ (
    .A(_025_),
    .B(STP[0]),
    .Y(_026_)
  );
  NAND _250_ (
    .A(_023_),
    .B(_002_),
    .Y(_027_)
  );
  NAND _251_ (
    .A(muxCTRL[1]),
    .B(muxCTRL[0]),
    .Y(_028_)
  );
  NOR _252_ (
    .A(_028_),
    .B(_027_),
    .Y(_029_)
  );
  NAND _253_ (
    .A(_029_),
    .B(SKP[0]),
    .Y(_030_)
  );
  NAND _254_ (
    .A(_030_),
    .B(_026_),
    .Y(_031_)
  );
  NAND _255_ (
    .A(_003_),
    .B(muxCTRL[0]),
    .Y(_032_)
  );
  NOR _256_ (
    .A(_032_),
    .B(_008_),
    .Y(_033_)
  );
  NAND _257_ (
    .A(_033_),
    .B(IDL[0]),
    .Y(_034_)
  );
  NOR _258_ (
    .A(_032_),
    .B(_027_),
    .Y(_035_)
  );
  NAND _259_ (
    .A(_035_),
    .B(COM[0]),
    .Y(_036_)
  );
  NAND _260_ (
    .A(_036_),
    .B(_034_),
    .Y(_037_)
  );
  NOR _261_ (
    .A(_037_),
    .B(_031_),
    .Y(_038_)
  );
  NOR _262_ (
    .A(_028_),
    .B(_024_),
    .Y(_039_)
  );
  NAND _263_ (
    .A(_039_),
    .B(EDB[0]),
    .Y(_040_)
  );
  NAND _264_ (
    .A(_040_),
    .B(_001_),
    .Y(_041_)
  );
  NAND _265_ (
    .A(muxCTRL[1]),
    .B(_006_),
    .Y(_042_)
  );
  NOR _266_ (
    .A(_042_),
    .B(_024_),
    .Y(_043_)
  );
  NAND _267_ (
    .A(_043_),
    .B(END[0]),
    .Y(_044_)
  );
  NOR _268_ (
    .A(_042_),
    .B(_027_),
    .Y(_045_)
  );
  NAND _269_ (
    .A(_045_),
    .B(PAD[0]),
    .Y(_046_)
  );
  NAND _270_ (
    .A(_046_),
    .B(_044_),
    .Y(_047_)
  );
  NOR _271_ (
    .A(_047_),
    .B(_041_),
    .Y(_048_)
  );
  NAND _272_ (
    .A(_048_),
    .B(_038_),
    .Y(_049_)
  );
  NOR _273_ (
    .A(_049_),
    .B(_022_),
    .Y(_050_)
  );
  NOR _274_ (
    .A(_050_),
    .B(_005_),
    .Y(_000_[0])
  );
  NOR _275_ (
    .A(_001_),
    .B(muxOUT[1]),
    .Y(_051_)
  );
  NAND _276_ (
    .A(_029_),
    .B(SKP[1]),
    .Y(_052_)
  );
  NOT _277_ (
    .A(EDB[1]),
    .Y(_053_)
  );
  NOT _278_ (
    .A(_028_),
    .Y(_054_)
  );
  NAND _279_ (
    .A(_054_),
    .B(_017_),
    .Y(_055_)
  );
  NOR _280_ (
    .A(_055_),
    .B(_053_),
    .Y(_056_)
  );
  NOT _281_ (
    .A(COM[1]),
    .Y(_057_)
  );
  NAND _282_ (
    .A(_018_),
    .B(_013_),
    .Y(_058_)
  );
  NOR _283_ (
    .A(_058_),
    .B(_057_),
    .Y(_059_)
  );
  NOR _284_ (
    .A(_059_),
    .B(_056_),
    .Y(_060_)
  );
  NAND _285_ (
    .A(_060_),
    .B(_052_),
    .Y(_061_)
  );
  NAND _286_ (
    .A(_025_),
    .B(STP[1]),
    .Y(_062_)
  );
  NAND _287_ (
    .A(_043_),
    .B(END[1]),
    .Y(_063_)
  );
  NAND _288_ (
    .A(_063_),
    .B(_062_),
    .Y(_064_)
  );
  NAND _289_ (
    .A(_009_),
    .B(FTS[1]),
    .Y(_065_)
  );
  NOR _290_ (
    .A(_032_),
    .B(_024_),
    .Y(_066_)
  );
  NAND _291_ (
    .A(_066_),
    .B(SDP[1]),
    .Y(_067_)
  );
  NAND _292_ (
    .A(_067_),
    .B(_065_),
    .Y(_068_)
  );
  NOR _293_ (
    .A(_068_),
    .B(_064_),
    .Y(_069_)
  );
  NAND _294_ (
    .A(_033_),
    .B(IDL[1]),
    .Y(_070_)
  );
  NAND _295_ (
    .A(_070_),
    .B(_001_),
    .Y(_071_)
  );
  NOR _296_ (
    .A(_027_),
    .B(_007_),
    .Y(_072_)
  );
  NAND _297_ (
    .A(_072_),
    .B(TLP[1]),
    .Y(_073_)
  );
  NAND _298_ (
    .A(_045_),
    .B(PAD[1]),
    .Y(_074_)
  );
  NAND _299_ (
    .A(_074_),
    .B(_073_),
    .Y(_075_)
  );
  NOR _300_ (
    .A(_075_),
    .B(_071_),
    .Y(_076_)
  );
  NAND _301_ (
    .A(_076_),
    .B(_069_),
    .Y(_077_)
  );
  NOR _302_ (
    .A(_077_),
    .B(_061_),
    .Y(_078_)
  );
  NOR _303_ (
    .A(_078_),
    .B(_051_),
    .Y(_000_[1])
  );
  NOR _304_ (
    .A(_001_),
    .B(muxOUT[2]),
    .Y(_079_)
  );
  NAND _305_ (
    .A(_009_),
    .B(FTS[2]),
    .Y(_080_)
  );
  NOT _306_ (
    .A(IDL[2]),
    .Y(_081_)
  );
  NOR _307_ (
    .A(_023_),
    .B(muxCTRL[2]),
    .Y(_082_)
  );
  NAND _308_ (
    .A(_018_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _309_ (
    .A(_083_),
    .B(_081_),
    .Y(_084_)
  );
  NOT _310_ (
    .A(EDB[2]),
    .Y(_085_)
  );
  NOR _311_ (
    .A(_055_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _312_ (
    .A(_086_),
    .B(_084_),
    .Y(_087_)
  );
  NAND _313_ (
    .A(_087_),
    .B(_080_),
    .Y(_088_)
  );
  NAND _314_ (
    .A(_066_),
    .B(SDP[2]),
    .Y(_089_)
  );
  NAND _315_ (
    .A(_025_),
    .B(STP[2]),
    .Y(_090_)
  );
  NAND _316_ (
    .A(_090_),
    .B(_089_),
    .Y(_091_)
  );
  NAND _317_ (
    .A(_043_),
    .B(END[2]),
    .Y(_092_)
  );
  NAND _318_ (
    .A(_072_),
    .B(TLP[2]),
    .Y(_093_)
  );
  NAND _319_ (
    .A(_093_),
    .B(_092_),
    .Y(_094_)
  );
  NOR _320_ (
    .A(_094_),
    .B(_091_),
    .Y(_095_)
  );
  NAND _321_ (
    .A(_029_),
    .B(SKP[2]),
    .Y(_096_)
  );
  NAND _322_ (
    .A(_035_),
    .B(COM[2]),
    .Y(_097_)
  );
  NAND _323_ (
    .A(_097_),
    .B(_096_),
    .Y(_098_)
  );
  NAND _324_ (
    .A(_045_),
    .B(PAD[2]),
    .Y(_099_)
  );
  NAND _325_ (
    .A(_099_),
    .B(_001_),
    .Y(_100_)
  );
  NOR _326_ (
    .A(_100_),
    .B(_098_),
    .Y(_101_)
  );
  NAND _327_ (
    .A(_101_),
    .B(_095_),
    .Y(_102_)
  );
  NOR _328_ (
    .A(_102_),
    .B(_088_),
    .Y(_103_)
  );
  NOR _329_ (
    .A(_103_),
    .B(_079_),
    .Y(_000_[2])
  );
  NOR _330_ (
    .A(_001_),
    .B(muxOUT[3]),
    .Y(_104_)
  );
  NAND _331_ (
    .A(_025_),
    .B(STP[3]),
    .Y(_105_)
  );
  NOT _332_ (
    .A(PAD[3]),
    .Y(_106_)
  );
  NOR _333_ (
    .A(_003_),
    .B(muxCTRL[0]),
    .Y(_107_)
  );
  NAND _334_ (
    .A(_107_),
    .B(_013_),
    .Y(_108_)
  );
  NOR _335_ (
    .A(_108_),
    .B(_106_),
    .Y(_109_)
  );
  NOT _336_ (
    .A(SDP[3]),
    .Y(_110_)
  );
  NOR _337_ (
    .A(_019_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _338_ (
    .A(_111_),
    .B(_109_),
    .Y(_112_)
  );
  NAND _339_ (
    .A(_112_),
    .B(_105_),
    .Y(_113_)
  );
  NAND _340_ (
    .A(_043_),
    .B(END[3]),
    .Y(_114_)
  );
  NAND _341_ (
    .A(_029_),
    .B(SKP[3]),
    .Y(_115_)
  );
  NAND _342_ (
    .A(_115_),
    .B(_114_),
    .Y(_116_)
  );
  NAND _343_ (
    .A(_039_),
    .B(EDB[3]),
    .Y(_117_)
  );
  NAND _344_ (
    .A(_009_),
    .B(FTS[3]),
    .Y(_118_)
  );
  NAND _345_ (
    .A(_118_),
    .B(_117_),
    .Y(_119_)
  );
  NOR _346_ (
    .A(_119_),
    .B(_116_),
    .Y(_120_)
  );
  NAND _347_ (
    .A(_033_),
    .B(IDL[3]),
    .Y(_121_)
  );
  NAND _348_ (
    .A(_121_),
    .B(_001_),
    .Y(_122_)
  );
  NAND _349_ (
    .A(_072_),
    .B(TLP[3]),
    .Y(_123_)
  );
  NAND _350_ (
    .A(_035_),
    .B(COM[3]),
    .Y(_124_)
  );
  NAND _351_ (
    .A(_124_),
    .B(_123_),
    .Y(_125_)
  );
  NOR _352_ (
    .A(_125_),
    .B(_122_),
    .Y(_126_)
  );
  NAND _353_ (
    .A(_126_),
    .B(_120_),
    .Y(_127_)
  );
  NOR _354_ (
    .A(_127_),
    .B(_113_),
    .Y(_128_)
  );
  NOR _355_ (
    .A(_128_),
    .B(_104_),
    .Y(_000_[3])
  );
  NOR _356_ (
    .A(_001_),
    .B(muxOUT[4]),
    .Y(_129_)
  );
  NAND _357_ (
    .A(_029_),
    .B(SKP[4]),
    .Y(_130_)
  );
  NOT _358_ (
    .A(STP[4]),
    .Y(_131_)
  );
  NAND _359_ (
    .A(_017_),
    .B(_012_),
    .Y(_132_)
  );
  NOR _360_ (
    .A(_132_),
    .B(_131_),
    .Y(_133_)
  );
  NOT _361_ (
    .A(PAD[4]),
    .Y(_134_)
  );
  NOR _362_ (
    .A(_108_),
    .B(_134_),
    .Y(_135_)
  );
  NOR _363_ (
    .A(_135_),
    .B(_133_),
    .Y(_136_)
  );
  NAND _364_ (
    .A(_136_),
    .B(_130_),
    .Y(_137_)
  );
  NAND _365_ (
    .A(_066_),
    .B(SDP[4]),
    .Y(_138_)
  );
  NAND _366_ (
    .A(_072_),
    .B(TLP[4]),
    .Y(_139_)
  );
  NAND _367_ (
    .A(_139_),
    .B(_138_),
    .Y(_140_)
  );
  NAND _368_ (
    .A(_033_),
    .B(IDL[4]),
    .Y(_141_)
  );
  NAND _369_ (
    .A(_035_),
    .B(COM[4]),
    .Y(_142_)
  );
  NAND _370_ (
    .A(_142_),
    .B(_141_),
    .Y(_143_)
  );
  NOR _371_ (
    .A(_143_),
    .B(_140_),
    .Y(_144_)
  );
  NAND _372_ (
    .A(_009_),
    .B(FTS[4]),
    .Y(_145_)
  );
  NAND _373_ (
    .A(_145_),
    .B(_001_),
    .Y(_146_)
  );
  NAND _374_ (
    .A(_043_),
    .B(END[4]),
    .Y(_147_)
  );
  NAND _375_ (
    .A(_039_),
    .B(EDB[4]),
    .Y(_148_)
  );
  NAND _376_ (
    .A(_148_),
    .B(_147_),
    .Y(_149_)
  );
  NOR _377_ (
    .A(_149_),
    .B(_146_),
    .Y(_150_)
  );
  NAND _378_ (
    .A(_150_),
    .B(_144_),
    .Y(_151_)
  );
  NOR _379_ (
    .A(_151_),
    .B(_137_),
    .Y(_152_)
  );
  NOR _380_ (
    .A(_152_),
    .B(_129_),
    .Y(_000_[4])
  );
  NOR _381_ (
    .A(_001_),
    .B(muxOUT[5]),
    .Y(_153_)
  );
  NAND _382_ (
    .A(_033_),
    .B(IDL[5]),
    .Y(_154_)
  );
  NOT _383_ (
    .A(TLP[5]),
    .Y(_155_)
  );
  NOR _384_ (
    .A(_014_),
    .B(_155_),
    .Y(_156_)
  );
  NOT _385_ (
    .A(END[5]),
    .Y(_157_)
  );
  NAND _386_ (
    .A(_107_),
    .B(_017_),
    .Y(_158_)
  );
  NOR _387_ (
    .A(_158_),
    .B(_157_),
    .Y(_159_)
  );
  NOR _388_ (
    .A(_159_),
    .B(_156_),
    .Y(_160_)
  );
  NAND _389_ (
    .A(_160_),
    .B(_154_),
    .Y(_161_)
  );
  NAND _390_ (
    .A(_045_),
    .B(PAD[5]),
    .Y(_162_)
  );
  NAND _391_ (
    .A(_029_),
    .B(SKP[5]),
    .Y(_163_)
  );
  NAND _392_ (
    .A(_163_),
    .B(_162_),
    .Y(_164_)
  );
  NAND _393_ (
    .A(_039_),
    .B(EDB[5]),
    .Y(_165_)
  );
  NAND _394_ (
    .A(_066_),
    .B(SDP[5]),
    .Y(_166_)
  );
  NAND _395_ (
    .A(_166_),
    .B(_165_),
    .Y(_167_)
  );
  NOR _396_ (
    .A(_167_),
    .B(_164_),
    .Y(_168_)
  );
  NAND _397_ (
    .A(_025_),
    .B(STP[5]),
    .Y(_169_)
  );
  NAND _398_ (
    .A(_169_),
    .B(_001_),
    .Y(_170_)
  );
  NAND _399_ (
    .A(_009_),
    .B(FTS[5]),
    .Y(_171_)
  );
  NAND _400_ (
    .A(_035_),
    .B(COM[5]),
    .Y(_172_)
  );
  NAND _401_ (
    .A(_172_),
    .B(_171_),
    .Y(_173_)
  );
  NOR _402_ (
    .A(_173_),
    .B(_170_),
    .Y(_174_)
  );
  NAND _403_ (
    .A(_174_),
    .B(_168_),
    .Y(_175_)
  );
  NOR _404_ (
    .A(_175_),
    .B(_161_),
    .Y(_176_)
  );
  NOR _405_ (
    .A(_176_),
    .B(_153_),
    .Y(_000_[5])
  );
  NOR _406_ (
    .A(_001_),
    .B(muxOUT[6]),
    .Y(_177_)
  );
  NAND _407_ (
    .A(_035_),
    .B(COM[6]),
    .Y(_178_)
  );
  NOT _408_ (
    .A(FTS[6]),
    .Y(_179_)
  );
  NAND _409_ (
    .A(_082_),
    .B(_012_),
    .Y(_180_)
  );
  NOR _410_ (
    .A(_180_),
    .B(_179_),
    .Y(_181_)
  );
  NOT _411_ (
    .A(STP[6]),
    .Y(_182_)
  );
  NOR _412_ (
    .A(_132_),
    .B(_182_),
    .Y(_183_)
  );
  NOR _413_ (
    .A(_183_),
    .B(_181_),
    .Y(_184_)
  );
  NAND _414_ (
    .A(_184_),
    .B(_178_),
    .Y(_185_)
  );
  NAND _415_ (
    .A(_043_),
    .B(END[6]),
    .Y(_186_)
  );
  NAND _416_ (
    .A(_029_),
    .B(SKP[6]),
    .Y(_187_)
  );
  NAND _417_ (
    .A(_187_),
    .B(_186_),
    .Y(_188_)
  );
  NAND _418_ (
    .A(_045_),
    .B(PAD[6]),
    .Y(_189_)
  );
  NAND _419_ (
    .A(_066_),
    .B(SDP[6]),
    .Y(_190_)
  );
  NAND _420_ (
    .A(_190_),
    .B(_189_),
    .Y(_191_)
  );
  NOR _421_ (
    .A(_191_),
    .B(_188_),
    .Y(_192_)
  );
  NAND _422_ (
    .A(_039_),
    .B(EDB[6]),
    .Y(_193_)
  );
  NAND _423_ (
    .A(_072_),
    .B(TLP[6]),
    .Y(_194_)
  );
  NAND _424_ (
    .A(_194_),
    .B(_193_),
    .Y(_195_)
  );
  NAND _425_ (
    .A(_033_),
    .B(IDL[6]),
    .Y(_196_)
  );
  NAND _426_ (
    .A(_196_),
    .B(_001_),
    .Y(_197_)
  );
  NOR _427_ (
    .A(_197_),
    .B(_195_),
    .Y(_198_)
  );
  NAND _428_ (
    .A(_198_),
    .B(_192_),
    .Y(_199_)
  );
  NOR _429_ (
    .A(_199_),
    .B(_185_),
    .Y(_200_)
  );
  NOR _430_ (
    .A(_200_),
    .B(_177_),
    .Y(_000_[6])
  );
  NOR _431_ (
    .A(_001_),
    .B(muxOUT[7]),
    .Y(_201_)
  );
  NAND _432_ (
    .A(_025_),
    .B(STP[7]),
    .Y(_202_)
  );
  NOT _433_ (
    .A(EDB[7]),
    .Y(_203_)
  );
  NOR _434_ (
    .A(_055_),
    .B(_203_),
    .Y(_204_)
  );
  NOT _435_ (
    .A(END[7]),
    .Y(_205_)
  );
  NOR _436_ (
    .A(_158_),
    .B(_205_),
    .Y(_206_)
  );
  NOR _437_ (
    .A(_206_),
    .B(_204_),
    .Y(_207_)
  );
  NAND _438_ (
    .A(_207_),
    .B(_202_),
    .Y(_208_)
  );
  NAND _439_ (
    .A(_072_),
    .B(TLP[7]),
    .Y(_209_)
  );
  NAND _440_ (
    .A(_029_),
    .B(SKP[7]),
    .Y(_210_)
  );
  NAND _441_ (
    .A(_210_),
    .B(_209_),
    .Y(_211_)
  );
  NAND _442_ (
    .A(_045_),
    .B(PAD[7]),
    .Y(_212_)
  );
  NAND _443_ (
    .A(_033_),
    .B(IDL[7]),
    .Y(_213_)
  );
  NAND _444_ (
    .A(_213_),
    .B(_212_),
    .Y(_214_)
  );
  NOR _445_ (
    .A(_214_),
    .B(_211_),
    .Y(_215_)
  );
  NAND _446_ (
    .A(_066_),
    .B(SDP[7]),
    .Y(_216_)
  );
  NAND _447_ (
    .A(_216_),
    .B(_001_),
    .Y(_217_)
  );
  NAND _448_ (
    .A(_035_),
    .B(COM[7]),
    .Y(_218_)
  );
  NAND _449_ (
    .A(_009_),
    .B(FTS[7]),
    .Y(_219_)
  );
  NAND _450_ (
    .A(_219_),
    .B(_218_),
    .Y(_220_)
  );
  NOR _451_ (
    .A(_220_),
    .B(_217_),
    .Y(_221_)
  );
  NAND _452_ (
    .A(_221_),
    .B(_215_),
    .Y(_222_)
  );
  NOR _453_ (
    .A(_222_),
    .B(_208_),
    .Y(_223_)
  );
  NOR _454_ (
    .A(_223_),
    .B(_201_),
    .Y(_000_[7])
  );
  always @(posedge muxCLK)
      muxOUT[0] <= _000_[0];
  always @(posedge muxCLK)
      muxOUT[1] <= _000_[1];
  always @(posedge muxCLK)
      muxOUT[2] <= _000_[2];
  always @(posedge muxCLK)
      muxOUT[3] <= _000_[3];
  always @(posedge muxCLK)
      muxOUT[4] <= _000_[4];
  always @(posedge muxCLK)
      muxOUT[5] <= _000_[5];
  always @(posedge muxCLK)
      muxOUT[6] <= _000_[6];
  always @(posedge muxCLK)
      muxOUT[7] <= _000_[7];
  always @(posedge muxCLK)
      muxVLD <= _001_;
endmodule

module mux4a1_synth(In0, In1, In2, In3, Sel, outmux);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  input [7:0] In0;
  input [7:0] In1;
  input [7:0] In2;
  input [7:0] In3;
  input [1:0] Sel;
  output [7:0] outmux;
  NOT _086_ (
    .A(In2[0]),
    .Y(_033_)
  );
  NOT _087_ (
    .A(Sel[0]),
    .Y(_034_)
  );
  NAND _088_ (
    .A(Sel[1]),
    .B(_034_),
    .Y(_035_)
  );
  NOR _089_ (
    .A(_035_),
    .B(_033_),
    .Y(_036_)
  );
  NOT _090_ (
    .A(In0[0]),
    .Y(_037_)
  );
  NOT _091_ (
    .A(Sel[1]),
    .Y(_038_)
  );
  NAND _092_ (
    .A(_038_),
    .B(_034_),
    .Y(_039_)
  );
  NOR _093_ (
    .A(_039_),
    .B(_037_),
    .Y(_040_)
  );
  NOR _094_ (
    .A(_040_),
    .B(_036_),
    .Y(_041_)
  );
  NOT _095_ (
    .A(In1[0]),
    .Y(_042_)
  );
  NAND _096_ (
    .A(_038_),
    .B(Sel[0]),
    .Y(_043_)
  );
  NOR _097_ (
    .A(_043_),
    .B(_042_),
    .Y(_044_)
  );
  NOT _098_ (
    .A(In3[0]),
    .Y(_045_)
  );
  NAND _099_ (
    .A(Sel[1]),
    .B(Sel[0]),
    .Y(_046_)
  );
  NOR _100_ (
    .A(_046_),
    .B(_045_),
    .Y(_047_)
  );
  NOR _101_ (
    .A(_047_),
    .B(_044_),
    .Y(_048_)
  );
  NAND _102_ (
    .A(_048_),
    .B(_041_),
    .Y(outmux[0])
  );
  NOT _103_ (
    .A(In3[1]),
    .Y(_049_)
  );
  NOR _104_ (
    .A(_046_),
    .B(_049_),
    .Y(_050_)
  );
  NOT _105_ (
    .A(In2[1]),
    .Y(_051_)
  );
  NOR _106_ (
    .A(_035_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _107_ (
    .A(_052_),
    .B(_050_),
    .Y(_053_)
  );
  NOT _108_ (
    .A(In0[1]),
    .Y(_054_)
  );
  NOR _109_ (
    .A(_039_),
    .B(_054_),
    .Y(_055_)
  );
  NOT _110_ (
    .A(In1[1]),
    .Y(_056_)
  );
  NOR _111_ (
    .A(_043_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _112_ (
    .A(_057_),
    .B(_055_),
    .Y(_058_)
  );
  NAND _113_ (
    .A(_058_),
    .B(_053_),
    .Y(outmux[1])
  );
  NOT _114_ (
    .A(In1[2]),
    .Y(_059_)
  );
  NOR _115_ (
    .A(_043_),
    .B(_059_),
    .Y(_060_)
  );
  NOT _116_ (
    .A(In2[2]),
    .Y(_061_)
  );
  NOR _117_ (
    .A(_035_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _118_ (
    .A(_062_),
    .B(_060_),
    .Y(_063_)
  );
  NOT _119_ (
    .A(In3[2]),
    .Y(_064_)
  );
  NOR _120_ (
    .A(_046_),
    .B(_064_),
    .Y(_065_)
  );
  NOT _121_ (
    .A(In0[2]),
    .Y(_066_)
  );
  NOR _122_ (
    .A(_039_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _123_ (
    .A(_067_),
    .B(_065_),
    .Y(_068_)
  );
  NAND _124_ (
    .A(_068_),
    .B(_063_),
    .Y(outmux[2])
  );
  NOT _125_ (
    .A(In3[3]),
    .Y(_069_)
  );
  NOR _126_ (
    .A(_046_),
    .B(_069_),
    .Y(_070_)
  );
  NOT _127_ (
    .A(In2[3]),
    .Y(_071_)
  );
  NOR _128_ (
    .A(_035_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _129_ (
    .A(_072_),
    .B(_070_),
    .Y(_073_)
  );
  NOT _130_ (
    .A(In0[3]),
    .Y(_074_)
  );
  NOR _131_ (
    .A(_039_),
    .B(_074_),
    .Y(_075_)
  );
  NOT _132_ (
    .A(In1[3]),
    .Y(_076_)
  );
  NOR _133_ (
    .A(_043_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _134_ (
    .A(_077_),
    .B(_075_),
    .Y(_078_)
  );
  NAND _135_ (
    .A(_078_),
    .B(_073_),
    .Y(outmux[3])
  );
  NOT _136_ (
    .A(In1[4]),
    .Y(_079_)
  );
  NOR _137_ (
    .A(_043_),
    .B(_079_),
    .Y(_080_)
  );
  NOT _138_ (
    .A(In2[4]),
    .Y(_081_)
  );
  NOR _139_ (
    .A(_035_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _140_ (
    .A(_082_),
    .B(_080_),
    .Y(_083_)
  );
  NOT _141_ (
    .A(In3[4]),
    .Y(_084_)
  );
  NOR _142_ (
    .A(_046_),
    .B(_084_),
    .Y(_085_)
  );
  NOT _143_ (
    .A(In0[4]),
    .Y(_000_)
  );
  NOR _144_ (
    .A(_039_),
    .B(_000_),
    .Y(_001_)
  );
  NOR _145_ (
    .A(_001_),
    .B(_085_),
    .Y(_002_)
  );
  NAND _146_ (
    .A(_002_),
    .B(_083_),
    .Y(outmux[4])
  );
  NOT _147_ (
    .A(In1[5]),
    .Y(_003_)
  );
  NOR _148_ (
    .A(_043_),
    .B(_003_),
    .Y(_004_)
  );
  NOT _149_ (
    .A(In2[5]),
    .Y(_005_)
  );
  NOR _150_ (
    .A(_035_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _151_ (
    .A(_006_),
    .B(_004_),
    .Y(_007_)
  );
  NOT _152_ (
    .A(In3[5]),
    .Y(_008_)
  );
  NOR _153_ (
    .A(_046_),
    .B(_008_),
    .Y(_009_)
  );
  NOT _154_ (
    .A(In0[5]),
    .Y(_010_)
  );
  NOR _155_ (
    .A(_039_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _156_ (
    .A(_011_),
    .B(_009_),
    .Y(_012_)
  );
  NAND _157_ (
    .A(_012_),
    .B(_007_),
    .Y(outmux[5])
  );
  NOT _158_ (
    .A(In0[6]),
    .Y(_013_)
  );
  NOR _159_ (
    .A(_039_),
    .B(_013_),
    .Y(_014_)
  );
  NOT _160_ (
    .A(In2[6]),
    .Y(_015_)
  );
  NOR _161_ (
    .A(_035_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _162_ (
    .A(_016_),
    .B(_014_),
    .Y(_017_)
  );
  NOT _163_ (
    .A(In3[6]),
    .Y(_018_)
  );
  NOR _164_ (
    .A(_046_),
    .B(_018_),
    .Y(_019_)
  );
  NOT _165_ (
    .A(In1[6]),
    .Y(_020_)
  );
  NOR _166_ (
    .A(_043_),
    .B(_020_),
    .Y(_021_)
  );
  NOR _167_ (
    .A(_021_),
    .B(_019_),
    .Y(_022_)
  );
  NAND _168_ (
    .A(_022_),
    .B(_017_),
    .Y(outmux[6])
  );
  NOT _169_ (
    .A(In3[7]),
    .Y(_023_)
  );
  NOR _170_ (
    .A(_046_),
    .B(_023_),
    .Y(_024_)
  );
  NOT _171_ (
    .A(In2[7]),
    .Y(_025_)
  );
  NOR _172_ (
    .A(_035_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _173_ (
    .A(_026_),
    .B(_024_),
    .Y(_027_)
  );
  NOT _174_ (
    .A(In0[7]),
    .Y(_028_)
  );
  NOR _175_ (
    .A(_039_),
    .B(_028_),
    .Y(_029_)
  );
  NOT _176_ (
    .A(In1[7]),
    .Y(_030_)
  );
  NOR _177_ (
    .A(_043_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _178_ (
    .A(_031_),
    .B(_029_),
    .Y(_032_)
  );
  NAND _179_ (
    .A(_032_),
    .B(_027_),
    .Y(outmux[7])
  );
endmodule

module mux_ctr_synth(valid_count, CLK, reset, CTR);
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  input CLK;
  output [2:0] CTR;
  reg [2:0] CTR;
  input reset;
  input valid_count;
  NAND _15_ (
    .A(valid_count),
    .B(CTR[0]),
    .Y(_14_)
  );
  NOT _16_ (
    .A(CTR[0]),
    .Y(_01_)
  );
  NOT _17_ (
    .A(valid_count),
    .Y(_02_)
  );
  NAND _18_ (
    .A(_02_),
    .B(_01_),
    .Y(_03_)
  );
  NAND _19_ (
    .A(_03_),
    .B(_14_),
    .Y(_04_)
  );
  NAND _20_ (
    .A(_04_),
    .B(reset),
    .Y(_00_[0])
  );
  NOR _21_ (
    .A(_02_),
    .B(_01_),
    .Y(_05_)
  );
  NAND _22_ (
    .A(_05_),
    .B(CTR[1]),
    .Y(_06_)
  );
  NOT _23_ (
    .A(CTR[1]),
    .Y(_07_)
  );
  NAND _24_ (
    .A(_14_),
    .B(_07_),
    .Y(_08_)
  );
  NAND _25_ (
    .A(_08_),
    .B(_06_),
    .Y(_09_)
  );
  NAND _26_ (
    .A(_09_),
    .B(reset),
    .Y(_00_[1])
  );
  NAND _27_ (
    .A(_06_),
    .B(CTR[2]),
    .Y(_10_)
  );
  NOT _28_ (
    .A(reset),
    .Y(_11_)
  );
  NOR _29_ (
    .A(_06_),
    .B(CTR[2]),
    .Y(_12_)
  );
  NOR _30_ (
    .A(_12_),
    .B(_11_),
    .Y(_13_)
  );
  NAND _31_ (
    .A(_13_),
    .B(_10_),
    .Y(_00_[2])
  );
  always @(posedge CLK)
      CTR[0] <= _00_[0];
  always @(posedge CLK)
      CTR[1] <= _00_[1];
  always @(posedge CLK)
      CTR[2] <= _00_[2];
endmodule

module mux_p2s_synth(sel, data_in, data_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  input [7:0] data_in;
  output data_out;
  input [2:0] sel;
  NAND _23_ (
    .A(data_in[7]),
    .B(sel[2]),
    .Y(_00_)
  );
  NOT _24_ (
    .A(sel[2]),
    .Y(_01_)
  );
  NAND _25_ (
    .A(data_in[3]),
    .B(_01_),
    .Y(_02_)
  );
  NAND _26_ (
    .A(_02_),
    .B(_00_),
    .Y(_03_)
  );
  NAND _27_ (
    .A(_03_),
    .B(sel[0]),
    .Y(_04_)
  );
  NOT _28_ (
    .A(sel[0]),
    .Y(_05_)
  );
  NOR _29_ (
    .A(data_in[2]),
    .B(sel[2]),
    .Y(_06_)
  );
  NOR _30_ (
    .A(data_in[6]),
    .B(_01_),
    .Y(_07_)
  );
  NOR _31_ (
    .A(_07_),
    .B(_06_),
    .Y(_08_)
  );
  NAND _32_ (
    .A(_08_),
    .B(_05_),
    .Y(_09_)
  );
  NAND _33_ (
    .A(_09_),
    .B(_04_),
    .Y(_10_)
  );
  NAND _34_ (
    .A(_10_),
    .B(sel[1]),
    .Y(_11_)
  );
  NOT _35_ (
    .A(sel[1]),
    .Y(_12_)
  );
  NAND _36_ (
    .A(data_in[1]),
    .B(_01_),
    .Y(_13_)
  );
  NAND _37_ (
    .A(data_in[5]),
    .B(sel[2]),
    .Y(_14_)
  );
  NAND _38_ (
    .A(_14_),
    .B(_13_),
    .Y(_15_)
  );
  NAND _39_ (
    .A(_15_),
    .B(sel[0]),
    .Y(_16_)
  );
  NOR _40_ (
    .A(data_in[0]),
    .B(sel[2]),
    .Y(_17_)
  );
  NOR _41_ (
    .A(data_in[4]),
    .B(_01_),
    .Y(_18_)
  );
  NOR _42_ (
    .A(_18_),
    .B(_17_),
    .Y(_19_)
  );
  NAND _43_ (
    .A(_19_),
    .B(_05_),
    .Y(_20_)
  );
  NAND _44_ (
    .A(_20_),
    .B(_16_),
    .Y(_21_)
  );
  NAND _45_ (
    .A(_21_),
    .B(_12_),
    .Y(_22_)
  );
  NAND _46_ (
    .A(_22_),
    .B(_11_),
    .Y(data_out)
  );
endmodule

module p2s_synth(IN_CLK_p2s, IN_LANE3_p2s, IN_LANE2_p2s, IN_LANE1_p2s, IN_LANE0_p2s, IN_CTR_p2s, IN_ENB_p2s, IN_VALID_BS, OUT_LANE_p2s);
  input IN_CLK_p2s;
  input [2:0] IN_CTR_p2s;
  input IN_ENB_p2s;
  input [7:0] IN_LANE0_p2s;
  input [7:0] IN_LANE1_p2s;
  input [7:0] IN_LANE2_p2s;
  input [7:0] IN_LANE3_p2s;
  input IN_VALID_BS;
  output [3:0] OUT_LANE_p2s;
  wire [7:0] Q0_p2s;
  wire [7:0] Q1_p2s;
  wire [7:0] Q2_p2s;
  wire [7:0] Q3_p2s;
  wire valid_ffd;
  ffd_p2s_synth \ffd_lane0[0]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE0_p2s[0]),
    .ENB(IN_ENB_p2s),
    .Q(Q0_p2s[0]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane0[1]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE0_p2s[1]),
    .ENB(IN_ENB_p2s),
    .Q(Q0_p2s[1]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane0[2]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE0_p2s[2]),
    .ENB(IN_ENB_p2s),
    .Q(Q0_p2s[2]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane0[3]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE0_p2s[3]),
    .ENB(IN_ENB_p2s),
    .Q(Q0_p2s[3]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane0[4]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE0_p2s[4]),
    .ENB(IN_ENB_p2s),
    .Q(Q0_p2s[4]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane0[5]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE0_p2s[5]),
    .ENB(IN_ENB_p2s),
    .Q(Q0_p2s[5]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane0[6]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE0_p2s[6]),
    .ENB(IN_ENB_p2s),
    .Q(Q0_p2s[6]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane0[7]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE0_p2s[7]),
    .ENB(IN_ENB_p2s),
    .Q(Q0_p2s[7]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane1[0]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE1_p2s[0]),
    .ENB(IN_ENB_p2s),
    .Q(Q1_p2s[0]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane1[1]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE1_p2s[1]),
    .ENB(IN_ENB_p2s),
    .Q(Q1_p2s[1]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane1[2]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE1_p2s[2]),
    .ENB(IN_ENB_p2s),
    .Q(Q1_p2s[2]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane1[3]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE1_p2s[3]),
    .ENB(IN_ENB_p2s),
    .Q(Q1_p2s[3]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane1[4]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE1_p2s[4]),
    .ENB(IN_ENB_p2s),
    .Q(Q1_p2s[4]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane1[5]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE1_p2s[5]),
    .ENB(IN_ENB_p2s),
    .Q(Q1_p2s[5]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane1[6]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE1_p2s[6]),
    .ENB(IN_ENB_p2s),
    .Q(Q1_p2s[6]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane1[7]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE1_p2s[7]),
    .ENB(IN_ENB_p2s),
    .Q(Q1_p2s[7]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane2[0]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE2_p2s[0]),
    .ENB(IN_ENB_p2s),
    .Q(Q2_p2s[0]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane2[1]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE2_p2s[1]),
    .ENB(IN_ENB_p2s),
    .Q(Q2_p2s[1]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane2[2]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE2_p2s[2]),
    .ENB(IN_ENB_p2s),
    .Q(Q2_p2s[2]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane2[3]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE2_p2s[3]),
    .ENB(IN_ENB_p2s),
    .Q(Q2_p2s[3]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane2[4]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE2_p2s[4]),
    .ENB(IN_ENB_p2s),
    .Q(Q2_p2s[4]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane2[5]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE2_p2s[5]),
    .ENB(IN_ENB_p2s),
    .Q(Q2_p2s[5]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane2[6]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE2_p2s[6]),
    .ENB(IN_ENB_p2s),
    .Q(Q2_p2s[6]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane2[7]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE2_p2s[7]),
    .ENB(IN_ENB_p2s),
    .Q(Q2_p2s[7]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane3[0]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE3_p2s[0]),
    .ENB(IN_ENB_p2s),
    .Q(Q3_p2s[0]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane3[1]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE3_p2s[1]),
    .ENB(IN_ENB_p2s),
    .Q(Q3_p2s[1]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane3[2]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE3_p2s[2]),
    .ENB(IN_ENB_p2s),
    .Q(Q3_p2s[2]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane3[3]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE3_p2s[3]),
    .ENB(IN_ENB_p2s),
    .Q(Q3_p2s[3]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane3[4]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE3_p2s[4]),
    .ENB(IN_ENB_p2s),
    .Q(Q3_p2s[4]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane3[5]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE3_p2s[5]),
    .ENB(IN_ENB_p2s),
    .Q(Q3_p2s[5]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth \ffd_lane3[6]  (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE3_p2s[6]),
    .ENB(IN_ENB_p2s),
    .Q(Q3_p2s[6]),
    .valid_in(valid_ffd)
  );
  ffd_p2s_synth ffd_valid (
    .CLK(IN_CLK_p2s),
    .D(IN_LANE3_p2s[7]),
    .ENB(IN_ENB_p2s),
    .Q(Q3_p2s[7]),
    .valid_in(IN_VALID_BS),
    .valid_out(valid_ffd)
  );
  mux_p2s_synth mux_lane0 (
    .data_in(Q0_p2s),
    .data_out(OUT_LANE_p2s[0]),
    .sel(IN_CTR_p2s)
  );
  mux_p2s_synth mux_lane1 (
    .data_in(Q1_p2s),
    .data_out(OUT_LANE_p2s[1]),
    .sel(IN_CTR_p2s)
  );
  mux_p2s_synth mux_lane2 (
    .data_in(Q2_p2s),
    .data_out(OUT_LANE_p2s[2]),
    .sel(IN_CTR_p2s)
  );
  mux_p2s_synth mux_lane3 (
    .data_in(Q3_p2s),
    .data_out(OUT_LANE_p2s[3]),
    .sel(IN_CTR_p2s)
  );
endmodule

module p2s_s2p_synth(IN_CLK_2MHz, IN_CLK_250KHz, IN_LANE3, IN_LANE2, IN_LANE1, IN_LANE0, IN_ENB_TX, IN_RESET_TX, IN_VALID_TX, IN_ENB_RX, OUT_LANE3, OUT_LANE2, OUT_LANE1, OUT_LANE0);
  wire [1:0] CLK_RX;
  wire [2:0] CTR_TX;
  input IN_CLK_250KHz;
  input IN_CLK_2MHz;
  input IN_ENB_RX;
  input IN_ENB_TX;
  input [7:0] IN_LANE0;
  input [7:0] IN_LANE1;
  input [7:0] IN_LANE2;
  input [7:0] IN_LANE3;
  input IN_RESET_TX;
  input IN_VALID_TX;
  wire [3:0] LANE;
  output [7:0] OUT_LANE0;
  output [7:0] OUT_LANE1;
  output [7:0] OUT_LANE2;
  output [7:0] OUT_LANE3;
  mux_ctr_synth ctr_tx_cond (
    .CLK(IN_CLK_2MHz),
    .CTR(CTR_TX),
    .reset(IN_RESET_TX),
    .valid_count(IN_VALID_TX)
  );
  s2p_synth low_rx_cond (
    .IN_CLK_s2p({ IN_CLK_250KHz, IN_CLK_2MHz }),
    .IN_DIR_s2p(1'b1),
    .IN_ENB_s2p(IN_ENB_RX),
    .IN_LANE_s2p(LANE),
    .IN_MODO_s2p(2'b00),
    .OUT_LANE0_s2p(OUT_LANE0),
    .OUT_LANE1_s2p(OUT_LANE1),
    .OUT_LANE2_s2p(OUT_LANE2),
    .OUT_LANE3_s2p(OUT_LANE3)
  );
  p2s_synth low_tx_cond (
    .IN_CLK_p2s(IN_CLK_2MHz),
    .IN_CTR_p2s(CTR_TX),
    .IN_ENB_p2s(IN_ENB_TX),
    .IN_LANE0_p2s(IN_LANE0),
    .IN_LANE1_p2s(IN_LANE1),
    .IN_LANE2_p2s(IN_LANE2),
    .IN_LANE3_p2s(IN_LANE3),
    .IN_VALID_BS(IN_VALID_TX),
    .OUT_LANE_p2s(LANE)
  );
  assign CLK_RX = { IN_CLK_250KHz, IN_CLK_2MHz };
endmodule

module pcie_synth(IN_COM, IN_PAD, IN_SKP, IN_STP, IN_SDP, IN_END, IN_EDB, IN_FTS, IN_IDL, IN_TLP, IN_CTRL, IN_CLK_2MHz, IN_RESET_CLK, IN_ENB_TX_RX, OUT_DATA);
  input IN_CLK_2MHz;
  input [7:0] IN_COM;
  input [3:0] IN_CTRL;
  input [7:0] IN_EDB;
  input IN_ENB_TX_RX;
  input [7:0] IN_END;
  input [7:0] IN_FTS;
  input [7:0] IN_IDL;
  input [7:0] IN_PAD;
  input IN_RESET_CLK;
  input [7:0] IN_SDP;
  input [7:0] IN_SKP;
  input [7:0] IN_STP;
  input [7:0] IN_TLP;
  output [7:0] OUT_DATA;
endmodule

module s2p_synth(IN_CLK_s2p, IN_LANE_s2p, IN_MODO_s2p, IN_DIR_s2p, IN_ENB_s2p, OUT_LANE3_s2p, OUT_LANE2_s2p, OUT_LANE1_s2p, OUT_LANE0_s2p);
  input [1:0] IN_CLK_s2p;
  input IN_DIR_s2p;
  input IN_ENB_s2p;
  input [3:0] IN_LANE_s2p;
  input [1:0] IN_MODO_s2p;
  output [7:0] OUT_LANE0_s2p;
  output [7:0] OUT_LANE1_s2p;
  output [7:0] OUT_LANE2_s2p;
  output [7:0] OUT_LANE3_s2p;
  wire [7:0] P0_synth_s2p;
  wire [7:0] P1_synth_s2p;
  wire [7:0] P2_synth_s2p;
  wire [7:0] P3_synth_s2p;
  ffd_s2p_synth \ffd_lane0[0]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P0_synth_s2p[0]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE0_s2p[0])
  );
  ffd_s2p_synth \ffd_lane0[1]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P0_synth_s2p[1]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE0_s2p[1])
  );
  ffd_s2p_synth \ffd_lane0[2]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P0_synth_s2p[2]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE0_s2p[2])
  );
  ffd_s2p_synth \ffd_lane0[3]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P0_synth_s2p[3]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE0_s2p[3])
  );
  ffd_s2p_synth \ffd_lane0[4]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P0_synth_s2p[4]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE0_s2p[4])
  );
  ffd_s2p_synth \ffd_lane0[5]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P0_synth_s2p[5]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE0_s2p[5])
  );
  ffd_s2p_synth \ffd_lane0[6]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P0_synth_s2p[6]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE0_s2p[6])
  );
  ffd_s2p_synth \ffd_lane0[7]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P0_synth_s2p[7]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE0_s2p[7])
  );
  ffd_s2p_synth \ffd_lane1[0]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P1_synth_s2p[0]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE1_s2p[0])
  );
  ffd_s2p_synth \ffd_lane1[1]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P1_synth_s2p[1]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE1_s2p[1])
  );
  ffd_s2p_synth \ffd_lane1[2]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P1_synth_s2p[2]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE1_s2p[2])
  );
  ffd_s2p_synth \ffd_lane1[3]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P1_synth_s2p[3]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE1_s2p[3])
  );
  ffd_s2p_synth \ffd_lane1[4]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P1_synth_s2p[4]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE1_s2p[4])
  );
  ffd_s2p_synth \ffd_lane1[5]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P1_synth_s2p[5]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE1_s2p[5])
  );
  ffd_s2p_synth \ffd_lane1[6]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P1_synth_s2p[6]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE1_s2p[6])
  );
  ffd_s2p_synth \ffd_lane1[7]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P1_synth_s2p[7]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE1_s2p[7])
  );
  ffd_s2p_synth \ffd_lane2[0]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P2_synth_s2p[0]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE2_s2p[0])
  );
  ffd_s2p_synth \ffd_lane2[1]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P2_synth_s2p[1]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE2_s2p[1])
  );
  ffd_s2p_synth \ffd_lane2[2]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P2_synth_s2p[2]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE2_s2p[2])
  );
  ffd_s2p_synth \ffd_lane2[3]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P2_synth_s2p[3]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE2_s2p[3])
  );
  ffd_s2p_synth \ffd_lane2[4]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P2_synth_s2p[4]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE2_s2p[4])
  );
  ffd_s2p_synth \ffd_lane2[5]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P2_synth_s2p[5]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE2_s2p[5])
  );
  ffd_s2p_synth \ffd_lane2[6]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P2_synth_s2p[6]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE2_s2p[6])
  );
  ffd_s2p_synth \ffd_lane2[7]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P2_synth_s2p[7]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE2_s2p[7])
  );
  ffd_s2p_synth \ffd_lane3[0]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P3_synth_s2p[0]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE3_s2p[0])
  );
  ffd_s2p_synth \ffd_lane3[1]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P3_synth_s2p[1]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE3_s2p[1])
  );
  ffd_s2p_synth \ffd_lane3[2]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P3_synth_s2p[2]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE3_s2p[2])
  );
  ffd_s2p_synth \ffd_lane3[3]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P3_synth_s2p[3]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE3_s2p[3])
  );
  ffd_s2p_synth \ffd_lane3[4]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P3_synth_s2p[4]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE3_s2p[4])
  );
  ffd_s2p_synth \ffd_lane3[5]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P3_synth_s2p[5]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE3_s2p[5])
  );
  ffd_s2p_synth \ffd_lane3[6]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P3_synth_s2p[6]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE3_s2p[6])
  );
  ffd_s2p_synth \ffd_lane3[7]  (
    .CLK(IN_CLK_s2p[1]),
    .D(P3_synth_s2p[7]),
    .ENB(IN_ENB_s2p),
    .Q(OUT_LANE3_s2p[7])
  );
  s2p_reg_synth reg_lane0 (
    .CLK(IN_CLK_s2p[0]),
    .DIR(IN_DIR_s2p),
    .ENB(IN_ENB_s2p),
    .MODO(IN_MODO_s2p),
    .Q(P0_synth_s2p),
    .S_IN(IN_LANE_s2p[0])
  );
  s2p_reg_synth reg_lane1 (
    .CLK(IN_CLK_s2p[0]),
    .DIR(IN_DIR_s2p),
    .ENB(IN_ENB_s2p),
    .MODO(IN_MODO_s2p),
    .Q(P1_synth_s2p),
    .S_IN(IN_LANE_s2p[1])
  );
  s2p_reg_synth reg_lane2 (
    .CLK(IN_CLK_s2p[0]),
    .DIR(IN_DIR_s2p),
    .ENB(IN_ENB_s2p),
    .MODO(IN_MODO_s2p),
    .Q(P2_synth_s2p),
    .S_IN(IN_LANE_s2p[2])
  );
  s2p_reg_synth reg_lane3 (
    .CLK(IN_CLK_s2p[0]),
    .DIR(IN_DIR_s2p),
    .ENB(IN_ENB_s2p),
    .MODO(IN_MODO_s2p),
    .Q(P3_synth_s2p),
    .S_IN(IN_LANE_s2p[3])
  );
endmodule

module s2p_reg_synth(D, MODO, CLK, ENB, DIR, S_IN, Q, S_OUT);
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  input CLK;
  input [7:0] D;
  input DIR;
  input ENB;
  input [1:0] MODO;
  output [7:0] Q;
  reg [7:0] Q;
  input S_IN;
  output S_OUT;
  reg S_OUT;
  NOT _085_ (
    .A(ENB),
    .Y(_023_)
  );
  NAND _086_ (
    .A(_023_),
    .B(S_OUT),
    .Y(_024_)
  );
  NOT _087_ (
    .A(DIR),
    .Y(_025_)
  );
  NAND _088_ (
    .A(_025_),
    .B(Q[7]),
    .Y(_026_)
  );
  NAND _089_ (
    .A(DIR),
    .B(Q[0]),
    .Y(_027_)
  );
  NAND _090_ (
    .A(_027_),
    .B(_026_),
    .Y(_028_)
  );
  NOR _091_ (
    .A(MODO[0]),
    .B(MODO[1]),
    .Y(_029_)
  );
  NOT _092_ (
    .A(_029_),
    .Y(_030_)
  );
  NOR _093_ (
    .A(_030_),
    .B(_023_),
    .Y(_031_)
  );
  NAND _094_ (
    .A(_031_),
    .B(_028_),
    .Y(_032_)
  );
  NAND _095_ (
    .A(_032_),
    .B(_024_),
    .Y(_001_)
  );
  NOR _096_ (
    .A(ENB),
    .B(Q[0]),
    .Y(_033_)
  );
  NOT _097_ (
    .A(MODO[0]),
    .Y(_034_)
  );
  NOR _098_ (
    .A(_034_),
    .B(MODO[1]),
    .Y(_035_)
  );
  NAND _099_ (
    .A(Q[1]),
    .B(DIR),
    .Y(_036_)
  );
  NAND _100_ (
    .A(_036_),
    .B(_026_),
    .Y(_037_)
  );
  NAND _101_ (
    .A(_037_),
    .B(_035_),
    .Y(_038_)
  );
  NAND _102_ (
    .A(D[0]),
    .B(MODO[1]),
    .Y(_039_)
  );
  NAND _103_ (
    .A(_039_),
    .B(_038_),
    .Y(_040_)
  );
  NAND _104_ (
    .A(S_IN),
    .B(_025_),
    .Y(_041_)
  );
  NAND _105_ (
    .A(_041_),
    .B(_036_),
    .Y(_042_)
  );
  NAND _106_ (
    .A(_042_),
    .B(_029_),
    .Y(_043_)
  );
  NAND _107_ (
    .A(_043_),
    .B(ENB),
    .Y(_044_)
  );
  NOR _108_ (
    .A(_044_),
    .B(_040_),
    .Y(_045_)
  );
  NOR _109_ (
    .A(_045_),
    .B(_033_),
    .Y(_000_[0])
  );
  NAND _110_ (
    .A(D[1]),
    .B(MODO[1]),
    .Y(_046_)
  );
  NOT _111_ (
    .A(MODO[1]),
    .Y(_047_)
  );
  NAND _112_ (
    .A(_025_),
    .B(Q[0]),
    .Y(_048_)
  );
  NAND _113_ (
    .A(Q[2]),
    .B(DIR),
    .Y(_049_)
  );
  NAND _114_ (
    .A(_049_),
    .B(_048_),
    .Y(_050_)
  );
  NAND _115_ (
    .A(_050_),
    .B(_047_),
    .Y(_051_)
  );
  NAND _116_ (
    .A(_051_),
    .B(_046_),
    .Y(_052_)
  );
  NAND _117_ (
    .A(_052_),
    .B(ENB),
    .Y(_053_)
  );
  NAND _118_ (
    .A(Q[1]),
    .B(_023_),
    .Y(_054_)
  );
  NAND _119_ (
    .A(_054_),
    .B(_053_),
    .Y(_000_[1])
  );
  NAND _120_ (
    .A(D[2]),
    .B(MODO[1]),
    .Y(_055_)
  );
  NAND _121_ (
    .A(Q[1]),
    .B(_025_),
    .Y(_056_)
  );
  NAND _122_ (
    .A(Q[3]),
    .B(DIR),
    .Y(_057_)
  );
  NAND _123_ (
    .A(_057_),
    .B(_056_),
    .Y(_058_)
  );
  NAND _124_ (
    .A(_058_),
    .B(_047_),
    .Y(_059_)
  );
  NAND _125_ (
    .A(_059_),
    .B(_055_),
    .Y(_060_)
  );
  NAND _126_ (
    .A(_060_),
    .B(ENB),
    .Y(_061_)
  );
  NAND _127_ (
    .A(Q[2]),
    .B(_023_),
    .Y(_062_)
  );
  NAND _128_ (
    .A(_062_),
    .B(_061_),
    .Y(_000_[2])
  );
  NAND _129_ (
    .A(D[3]),
    .B(MODO[1]),
    .Y(_063_)
  );
  NAND _130_ (
    .A(Q[2]),
    .B(_025_),
    .Y(_064_)
  );
  NAND _131_ (
    .A(Q[4]),
    .B(DIR),
    .Y(_065_)
  );
  NAND _132_ (
    .A(_065_),
    .B(_064_),
    .Y(_066_)
  );
  NAND _133_ (
    .A(_066_),
    .B(_047_),
    .Y(_067_)
  );
  NAND _134_ (
    .A(_067_),
    .B(_063_),
    .Y(_068_)
  );
  NAND _135_ (
    .A(_068_),
    .B(ENB),
    .Y(_069_)
  );
  NAND _136_ (
    .A(Q[3]),
    .B(_023_),
    .Y(_070_)
  );
  NAND _137_ (
    .A(_070_),
    .B(_069_),
    .Y(_000_[3])
  );
  NAND _138_ (
    .A(D[4]),
    .B(MODO[1]),
    .Y(_071_)
  );
  NAND _139_ (
    .A(Q[3]),
    .B(_025_),
    .Y(_072_)
  );
  NAND _140_ (
    .A(Q[5]),
    .B(DIR),
    .Y(_073_)
  );
  NAND _141_ (
    .A(_073_),
    .B(_072_),
    .Y(_074_)
  );
  NAND _142_ (
    .A(_074_),
    .B(_047_),
    .Y(_075_)
  );
  NAND _143_ (
    .A(_075_),
    .B(_071_),
    .Y(_076_)
  );
  NAND _144_ (
    .A(_076_),
    .B(ENB),
    .Y(_077_)
  );
  NAND _145_ (
    .A(Q[4]),
    .B(_023_),
    .Y(_078_)
  );
  NAND _146_ (
    .A(_078_),
    .B(_077_),
    .Y(_000_[4])
  );
  NAND _147_ (
    .A(D[5]),
    .B(MODO[1]),
    .Y(_079_)
  );
  NAND _148_ (
    .A(Q[4]),
    .B(_025_),
    .Y(_080_)
  );
  NAND _149_ (
    .A(Q[6]),
    .B(DIR),
    .Y(_081_)
  );
  NAND _150_ (
    .A(_081_),
    .B(_080_),
    .Y(_082_)
  );
  NAND _151_ (
    .A(_082_),
    .B(_047_),
    .Y(_083_)
  );
  NAND _152_ (
    .A(_083_),
    .B(_079_),
    .Y(_084_)
  );
  NAND _153_ (
    .A(_084_),
    .B(ENB),
    .Y(_002_)
  );
  NAND _154_ (
    .A(Q[5]),
    .B(_023_),
    .Y(_003_)
  );
  NAND _155_ (
    .A(_003_),
    .B(_002_),
    .Y(_000_[5])
  );
  NAND _156_ (
    .A(D[6]),
    .B(MODO[1]),
    .Y(_004_)
  );
  NAND _157_ (
    .A(Q[5]),
    .B(_025_),
    .Y(_005_)
  );
  NAND _158_ (
    .A(DIR),
    .B(Q[7]),
    .Y(_006_)
  );
  NAND _159_ (
    .A(_006_),
    .B(_005_),
    .Y(_007_)
  );
  NAND _160_ (
    .A(_007_),
    .B(_047_),
    .Y(_008_)
  );
  NAND _161_ (
    .A(_008_),
    .B(_004_),
    .Y(_009_)
  );
  NAND _162_ (
    .A(_009_),
    .B(ENB),
    .Y(_010_)
  );
  NAND _163_ (
    .A(Q[6]),
    .B(_023_),
    .Y(_011_)
  );
  NAND _164_ (
    .A(_011_),
    .B(_010_),
    .Y(_000_[6])
  );
  NOR _165_ (
    .A(ENB),
    .B(Q[7]),
    .Y(_012_)
  );
  NAND _166_ (
    .A(Q[6]),
    .B(_025_),
    .Y(_013_)
  );
  NAND _167_ (
    .A(_013_),
    .B(_027_),
    .Y(_014_)
  );
  NAND _168_ (
    .A(_014_),
    .B(_035_),
    .Y(_015_)
  );
  NAND _169_ (
    .A(D[7]),
    .B(MODO[1]),
    .Y(_016_)
  );
  NAND _170_ (
    .A(_016_),
    .B(_015_),
    .Y(_017_)
  );
  NAND _171_ (
    .A(S_IN),
    .B(DIR),
    .Y(_018_)
  );
  NAND _172_ (
    .A(_018_),
    .B(_013_),
    .Y(_019_)
  );
  NAND _173_ (
    .A(_019_),
    .B(_029_),
    .Y(_020_)
  );
  NAND _174_ (
    .A(_020_),
    .B(ENB),
    .Y(_021_)
  );
  NOR _175_ (
    .A(_021_),
    .B(_017_),
    .Y(_022_)
  );
  NOR _176_ (
    .A(_022_),
    .B(_012_),
    .Y(_000_[7])
  );
  always @(posedge CLK)
      Q[0] <= _000_[0];
  always @(posedge CLK)
      Q[1] <= _000_[1];
  always @(posedge CLK)
      Q[2] <= _000_[2];
  always @(posedge CLK)
      Q[3] <= _000_[3];
  always @(posedge CLK)
      Q[4] <= _000_[4];
  always @(posedge CLK)
      Q[5] <= _000_[5];
  always @(posedge CLK)
      Q[6] <= _000_[6];
  always @(posedge CLK)
      Q[7] <= _000_[7];
  always @(posedge CLK)
      S_OUT <= _001_;
endmodule
