/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

module mux4_1_synth(VC_id, Data_Word, reset, data_out);
  input [3:0] Data_Word;
  input [1:0] VC_id;
  output data_out;
  input reset;
  assign data_out = 1'b0;
endmodule
