/* Generated by Yosys 0.7+560 (git sha1 d9a2b430, gcc 7.3.1 -fPIC -Os) */

module mux4_1_synth(VC_id, Data_Word, reset, data_out);
  input [3:0] Data_Word;
  input [1:0] VC_id;
  output data_out;
  input reset;
  assign data_out = 1'h0;
endmodule
