/* Generated by Yosys 0.7+560 (git sha1 d9a2b430, gcc 7.3.1 -fPIC -Os) */

module vc_table_synth(clk, reset, edit_weight, weight_assign, vc_assign, weight, vc_id_out);
  input clk;
  input edit_weight;
  input reset;
  input [1:0] vc_assign;
  output [1:0] vc_id_out;
  output [2:0] weight;
  input [2:0] weight_assign;
  assign vc_id_out = 2'h0;
  assign weight = 3'h0;
endmodule
