/* Generated by Yosys 0.7 (git sha1 UNKNOWN, clang 5.0.1 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -fPIC -Os) */

module vc_table_synth(clk, reset, edit_weight, weight_assign, vc_assign, weight, vc_id_out);
  wire [1:0] _000_;
  wire [2:0] _001_;
  wire [2:0] _002_;
  wire [2:0] _003_;
  wire [2:0] _004_;
  wire [2:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  input clk;
  input edit_weight;
  input reset;
  input [1:0] vc_assign;
  output [1:0] vc_id_out;
  reg [1:0] vc_id_out;
  output [2:0] weight;
  reg [2:0] weight;
  input [2:0] weight_assign;
  reg [2:0] weight_vc0;
  initial weight_vc0 = 3'b001;
  reg [2:0] weight_vc1;
  initial weight_vc1 = 3'b001;
  reg [2:0] weight_vc2;
  initial weight_vc2 = 3'b001;
  reg [2:0] weight_vc3;
  initial weight_vc3 = 3'b001;
  NAND _089_ (
    .A(vc_assign[1]),
    .B(vc_assign[0]),
    .Y(_045_)
  );
  NAND _090_ (
    .A(reset),
    .B(edit_weight),
    .Y(_046_)
  );
  NOR _091_ (
    .A(_046_),
    .B(_045_),
    .Y(_047_)
  );
  NAND _092_ (
    .A(_047_),
    .B(weight_assign[0]),
    .Y(_048_)
  );
  NOT _093_ (
    .A(_047_),
    .Y(_049_)
  );
  NAND _094_ (
    .A(_049_),
    .B(weight_vc3[0]),
    .Y(_050_)
  );
  NAND _095_ (
    .A(_050_),
    .B(_048_),
    .Y(_005_[0])
  );
  NAND _096_ (
    .A(_047_),
    .B(weight_assign[1]),
    .Y(_051_)
  );
  NAND _097_ (
    .A(_049_),
    .B(weight_vc3[1]),
    .Y(_052_)
  );
  NAND _098_ (
    .A(_052_),
    .B(_051_),
    .Y(_005_[1])
  );
  NAND _099_ (
    .A(_047_),
    .B(weight_assign[2]),
    .Y(_053_)
  );
  NAND _100_ (
    .A(_049_),
    .B(weight_vc3[2]),
    .Y(_054_)
  );
  NAND _101_ (
    .A(_054_),
    .B(_053_),
    .Y(_005_[2])
  );
  NOT _102_ (
    .A(vc_assign[0]),
    .Y(_055_)
  );
  NAND _103_ (
    .A(vc_assign[1]),
    .B(_055_),
    .Y(_056_)
  );
  NOR _104_ (
    .A(_056_),
    .B(_046_),
    .Y(_057_)
  );
  NAND _105_ (
    .A(_057_),
    .B(weight_assign[0]),
    .Y(_058_)
  );
  NOT _106_ (
    .A(_057_),
    .Y(_059_)
  );
  NAND _107_ (
    .A(_059_),
    .B(weight_vc2[0]),
    .Y(_060_)
  );
  NAND _108_ (
    .A(_060_),
    .B(_058_),
    .Y(_004_[0])
  );
  NAND _109_ (
    .A(_057_),
    .B(weight_assign[1]),
    .Y(_061_)
  );
  NAND _110_ (
    .A(_059_),
    .B(weight_vc2[1]),
    .Y(_062_)
  );
  NAND _111_ (
    .A(_062_),
    .B(_061_),
    .Y(_004_[1])
  );
  NAND _112_ (
    .A(_057_),
    .B(weight_assign[2]),
    .Y(_063_)
  );
  NAND _113_ (
    .A(_059_),
    .B(weight_vc2[2]),
    .Y(_064_)
  );
  NAND _114_ (
    .A(_064_),
    .B(_063_),
    .Y(_004_[2])
  );
  NOT _115_ (
    .A(_046_),
    .Y(_065_)
  );
  NOR _116_ (
    .A(vc_assign[1]),
    .B(_055_),
    .Y(_066_)
  );
  NAND _117_ (
    .A(_066_),
    .B(_065_),
    .Y(_067_)
  );
  NOT _118_ (
    .A(_067_),
    .Y(_068_)
  );
  NAND _119_ (
    .A(_068_),
    .B(weight_assign[0]),
    .Y(_069_)
  );
  NAND _120_ (
    .A(_067_),
    .B(weight_vc1[0]),
    .Y(_070_)
  );
  NAND _121_ (
    .A(_070_),
    .B(_069_),
    .Y(_003_[0])
  );
  NAND _122_ (
    .A(_068_),
    .B(weight_assign[1]),
    .Y(_071_)
  );
  NAND _123_ (
    .A(_067_),
    .B(weight_vc1[1]),
    .Y(_072_)
  );
  NAND _124_ (
    .A(_072_),
    .B(_071_),
    .Y(_003_[1])
  );
  NAND _125_ (
    .A(_068_),
    .B(weight_assign[2]),
    .Y(_073_)
  );
  NAND _126_ (
    .A(_067_),
    .B(weight_vc1[2]),
    .Y(_074_)
  );
  NAND _127_ (
    .A(_074_),
    .B(_073_),
    .Y(_003_[2])
  );
  NOT _128_ (
    .A(vc_assign[1]),
    .Y(_075_)
  );
  NAND _129_ (
    .A(_075_),
    .B(_055_),
    .Y(_076_)
  );
  NOR _130_ (
    .A(_076_),
    .B(_046_),
    .Y(_077_)
  );
  NAND _131_ (
    .A(_077_),
    .B(weight_assign[0]),
    .Y(_078_)
  );
  NOT _132_ (
    .A(_077_),
    .Y(_079_)
  );
  NAND _133_ (
    .A(_079_),
    .B(weight_vc0[0]),
    .Y(_080_)
  );
  NAND _134_ (
    .A(_080_),
    .B(_078_),
    .Y(_002_[0])
  );
  NAND _135_ (
    .A(_077_),
    .B(weight_assign[1]),
    .Y(_081_)
  );
  NAND _136_ (
    .A(_079_),
    .B(weight_vc0[1]),
    .Y(_082_)
  );
  NAND _137_ (
    .A(_082_),
    .B(_081_),
    .Y(_002_[1])
  );
  NAND _138_ (
    .A(_077_),
    .B(weight_assign[2]),
    .Y(_083_)
  );
  NAND _139_ (
    .A(_079_),
    .B(weight_vc0[2]),
    .Y(_084_)
  );
  NAND _140_ (
    .A(_084_),
    .B(_083_),
    .Y(_002_[2])
  );
  NAND _141_ (
    .A(reset),
    .B(vc_assign[0]),
    .Y(_085_)
  );
  NOR _142_ (
    .A(_085_),
    .B(edit_weight),
    .Y(_000_[0])
  );
  NAND _143_ (
    .A(reset),
    .B(vc_assign[1]),
    .Y(_086_)
  );
  NOR _144_ (
    .A(_086_),
    .B(edit_weight),
    .Y(_000_[1])
  );
  NOT _145_ (
    .A(edit_weight),
    .Y(_087_)
  );
  NOR _146_ (
    .A(_075_),
    .B(vc_assign[0]),
    .Y(_088_)
  );
  NAND _147_ (
    .A(_088_),
    .B(weight_vc2[0]),
    .Y(_006_)
  );
  NAND _148_ (
    .A(_006_),
    .B(_087_),
    .Y(_007_)
  );
  NOT _149_ (
    .A(weight_vc0[0]),
    .Y(_008_)
  );
  NOR _150_ (
    .A(_076_),
    .B(_008_),
    .Y(_009_)
  );
  NOT _151_ (
    .A(weight_vc3[0]),
    .Y(_010_)
  );
  NOR _152_ (
    .A(_045_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _153_ (
    .A(_011_),
    .B(_009_),
    .Y(_012_)
  );
  NAND _154_ (
    .A(_066_),
    .B(weight_vc1[0]),
    .Y(_013_)
  );
  NAND _155_ (
    .A(_013_),
    .B(_012_),
    .Y(_014_)
  );
  NOR _156_ (
    .A(_014_),
    .B(_007_),
    .Y(_015_)
  );
  NOT _157_ (
    .A(weight[0]),
    .Y(_016_)
  );
  NAND _158_ (
    .A(_016_),
    .B(edit_weight),
    .Y(_017_)
  );
  NAND _159_ (
    .A(_017_),
    .B(reset),
    .Y(_018_)
  );
  NOR _160_ (
    .A(_018_),
    .B(_015_),
    .Y(_001_[0])
  );
  NAND _161_ (
    .A(_066_),
    .B(weight_vc1[1]),
    .Y(_019_)
  );
  NOR _162_ (
    .A(vc_assign[1]),
    .B(vc_assign[0]),
    .Y(_020_)
  );
  NAND _163_ (
    .A(_020_),
    .B(weight_vc0[1]),
    .Y(_021_)
  );
  NAND _164_ (
    .A(_021_),
    .B(_019_),
    .Y(_022_)
  );
  NOT _165_ (
    .A(_045_),
    .Y(_023_)
  );
  NAND _166_ (
    .A(_023_),
    .B(weight_vc3[1]),
    .Y(_024_)
  );
  NOT _167_ (
    .A(weight_vc2[1]),
    .Y(_025_)
  );
  NOR _168_ (
    .A(_056_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _169_ (
    .A(_026_),
    .B(edit_weight),
    .Y(_027_)
  );
  NAND _170_ (
    .A(_027_),
    .B(_024_),
    .Y(_028_)
  );
  NOR _171_ (
    .A(_028_),
    .B(_022_),
    .Y(_029_)
  );
  NOT _172_ (
    .A(weight[1]),
    .Y(_030_)
  );
  NAND _173_ (
    .A(_030_),
    .B(edit_weight),
    .Y(_031_)
  );
  NAND _174_ (
    .A(_031_),
    .B(reset),
    .Y(_032_)
  );
  NOR _175_ (
    .A(_032_),
    .B(_029_),
    .Y(_001_[1])
  );
  NAND _176_ (
    .A(_066_),
    .B(weight_vc1[2]),
    .Y(_033_)
  );
  NAND _177_ (
    .A(_020_),
    .B(weight_vc0[2]),
    .Y(_034_)
  );
  NAND _178_ (
    .A(_034_),
    .B(_033_),
    .Y(_035_)
  );
  NAND _179_ (
    .A(_023_),
    .B(weight_vc3[2]),
    .Y(_036_)
  );
  NOT _180_ (
    .A(weight_vc2[2]),
    .Y(_037_)
  );
  NOR _181_ (
    .A(_056_),
    .B(_037_),
    .Y(_038_)
  );
  NOR _182_ (
    .A(_038_),
    .B(edit_weight),
    .Y(_039_)
  );
  NAND _183_ (
    .A(_039_),
    .B(_036_),
    .Y(_040_)
  );
  NOR _184_ (
    .A(_040_),
    .B(_035_),
    .Y(_041_)
  );
  NOT _185_ (
    .A(weight[2]),
    .Y(_042_)
  );
  NAND _186_ (
    .A(_042_),
    .B(edit_weight),
    .Y(_043_)
  );
  NAND _187_ (
    .A(_043_),
    .B(reset),
    .Y(_044_)
  );
  NOR _188_ (
    .A(_044_),
    .B(_041_),
    .Y(_001_[2])
  );
  always @(posedge clk)
      weight[0] <= _001_[0];
  always @(posedge clk)
      weight[1] <= _001_[1];
  always @(posedge clk)
      weight[2] <= _001_[2];
  always @(posedge clk)
      vc_id_out[0] <= _000_[0];
  always @(posedge clk)
      vc_id_out[1] <= _000_[1];
  always @(posedge clk)
      weight_vc0[0] <= _002_[0];
  always @(posedge clk)
      weight_vc0[1] <= _002_[1];
  always @(posedge clk)
      weight_vc0[2] <= _002_[2];
  always @(posedge clk)
      weight_vc1[0] <= _003_[0];
  always @(posedge clk)
      weight_vc1[1] <= _003_[1];
  always @(posedge clk)
      weight_vc1[2] <= _003_[2];
  always @(posedge clk)
      weight_vc2[0] <= _004_[0];
  always @(posedge clk)
      weight_vc2[1] <= _004_[1];
  always @(posedge clk)
      weight_vc2[2] <= _004_[2];
  always @(posedge clk)
      weight_vc3[0] <= _005_[0];
  always @(posedge clk)
      weight_vc3[1] <= _005_[1];
  always @(posedge clk)
      weight_vc3[2] <= _005_[2];
endmodule
