/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

module vc_table_synth(clk, reset, edit_weight, weight_assign, vc_assign, weight, vc_id_out);
  wire [1:0] _000_;
  wire [2:0] _001_;
  wire [2:0] _002_;
  wire [2:0] _003_;
  wire [2:0] _004_;
  wire [2:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  input clk;
  input edit_weight;
  input reset;
  input [1:0] vc_assign;
  output [1:0] vc_id_out;
  reg [1:0] vc_id_out;
  output [2:0] weight;
  reg [2:0] weight;
  input [2:0] weight_assign;
<<<<<<< HEAD
  assign vc = 2'b00;
  assign weight = 3'b000;
=======
  reg [2:0] weight_vc0 = 3'h1;
  reg [2:0] weight_vc1 = 3'h1;
  reg [2:0] weight_vc2 = 3'h1;
  reg [2:0] weight_vc3 = 3'h1;
  NOT _091_ (
    .A(vc_assign[0]),
    .Y(_043_)
  );
  NOT _092_ (
    .A(vc_assign[1]),
    .Y(_044_)
  );
  NOT _093_ (
    .A(weight_vc3[0]),
    .Y(_045_)
  );
  NOT _094_ (
    .A(edit_weight),
    .Y(_046_)
  );
  NOT _095_ (
    .A(reset),
    .Y(_047_)
  );
  NOT _096_ (
    .A(weight_vc2[1]),
    .Y(_048_)
  );
  NOT _097_ (
    .A(weight_vc2[2]),
    .Y(_049_)
  );
  NOT _098_ (
    .A(weight[0]),
    .Y(_050_)
  );
  NOT _099_ (
    .A(weight[1]),
    .Y(_051_)
  );
  NOT _100_ (
    .A(weight[2]),
    .Y(_052_)
  );
  NOR _101_ (
    .A(_043_),
    .B(_044_),
    .Y(_053_)
  );
  NAND _102_ (
    .A(vc_assign[0]),
    .B(vc_assign[1]),
    .Y(_054_)
  );
  NOR _103_ (
    .A(_046_),
    .B(_047_),
    .Y(_055_)
  );
  NAND _104_ (
    .A(edit_weight),
    .B(reset),
    .Y(_056_)
  );
  NOR _105_ (
    .A(_054_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _106_ (
    .A(_053_),
    .B(_055_),
    .Y(_058_)
  );
  NAND _107_ (
    .A(weight_assign[0]),
    .B(_057_),
    .Y(_059_)
  );
  NAND _108_ (
    .A(weight_vc3[0]),
    .B(_058_),
    .Y(_060_)
  );
  NAND _109_ (
    .A(_059_),
    .B(_060_),
    .Y(_005_[0])
  );
  NAND _110_ (
    .A(weight_assign[1]),
    .B(_057_),
    .Y(_061_)
  );
  NAND _111_ (
    .A(weight_vc3[1]),
    .B(_058_),
    .Y(_062_)
  );
  NAND _112_ (
    .A(_061_),
    .B(_062_),
    .Y(_005_[1])
  );
  NAND _113_ (
    .A(weight_assign[2]),
    .B(_057_),
    .Y(_063_)
  );
  NAND _114_ (
    .A(weight_vc3[2]),
    .B(_058_),
    .Y(_064_)
  );
  NAND _115_ (
    .A(_063_),
    .B(_064_),
    .Y(_005_[2])
  );
  NOR _116_ (
    .A(vc_assign[0]),
    .B(_044_),
    .Y(_065_)
  );
  NAND _117_ (
    .A(_043_),
    .B(vc_assign[1]),
    .Y(_066_)
  );
  NOR _118_ (
    .A(_056_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _119_ (
    .A(_055_),
    .B(_065_),
    .Y(_068_)
  );
  NAND _120_ (
    .A(weight_assign[0]),
    .B(_067_),
    .Y(_069_)
  );
  NAND _121_ (
    .A(weight_vc2[0]),
    .B(_068_),
    .Y(_070_)
  );
  NAND _122_ (
    .A(_069_),
    .B(_070_),
    .Y(_004_[0])
  );
  NAND _123_ (
    .A(weight_assign[1]),
    .B(_067_),
    .Y(_071_)
  );
  NAND _124_ (
    .A(weight_vc2[1]),
    .B(_068_),
    .Y(_072_)
  );
  NAND _125_ (
    .A(_071_),
    .B(_072_),
    .Y(_004_[1])
  );
  NAND _126_ (
    .A(weight_assign[2]),
    .B(_067_),
    .Y(_073_)
  );
  NAND _127_ (
    .A(weight_vc2[2]),
    .B(_068_),
    .Y(_074_)
  );
  NAND _128_ (
    .A(_073_),
    .B(_074_),
    .Y(_004_[2])
  );
  NOR _129_ (
    .A(_043_),
    .B(vc_assign[1]),
    .Y(_075_)
  );
  NOT _130_ (
    .A(_075_),
    .Y(_076_)
  );
  NOR _131_ (
    .A(_056_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _132_ (
    .A(_055_),
    .B(_075_),
    .Y(_078_)
  );
  NAND _133_ (
    .A(weight_assign[0]),
    .B(_077_),
    .Y(_079_)
  );
  NAND _134_ (
    .A(weight_vc1[0]),
    .B(_078_),
    .Y(_080_)
  );
  NAND _135_ (
    .A(_079_),
    .B(_080_),
    .Y(_003_[0])
  );
  NAND _136_ (
    .A(weight_assign[1]),
    .B(_077_),
    .Y(_081_)
  );
  NAND _137_ (
    .A(weight_vc1[1]),
    .B(_078_),
    .Y(_082_)
  );
  NAND _138_ (
    .A(_081_),
    .B(_082_),
    .Y(_003_[1])
  );
  NAND _139_ (
    .A(weight_assign[2]),
    .B(_077_),
    .Y(_083_)
  );
  NAND _140_ (
    .A(weight_vc1[2]),
    .B(_078_),
    .Y(_084_)
  );
  NAND _141_ (
    .A(_083_),
    .B(_084_),
    .Y(_003_[2])
  );
  NOR _142_ (
    .A(vc_assign[0]),
    .B(vc_assign[1]),
    .Y(_085_)
  );
  NOT _143_ (
    .A(_085_),
    .Y(_086_)
  );
  NOR _144_ (
    .A(_056_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _145_ (
    .A(_055_),
    .B(_085_),
    .Y(_088_)
  );
  NAND _146_ (
    .A(weight_assign[0]),
    .B(_087_),
    .Y(_089_)
  );
  NAND _147_ (
    .A(weight_vc0[0]),
    .B(_088_),
    .Y(_090_)
  );
  NAND _148_ (
    .A(_089_),
    .B(_090_),
    .Y(_002_[0])
  );
  NAND _149_ (
    .A(weight_assign[1]),
    .B(_087_),
    .Y(_006_)
  );
  NAND _150_ (
    .A(weight_vc0[1]),
    .B(_088_),
    .Y(_007_)
  );
  NAND _151_ (
    .A(_006_),
    .B(_007_),
    .Y(_002_[1])
  );
  NAND _152_ (
    .A(weight_assign[2]),
    .B(_087_),
    .Y(_008_)
  );
  NAND _153_ (
    .A(weight_vc0[2]),
    .B(_088_),
    .Y(_009_)
  );
  NAND _154_ (
    .A(_008_),
    .B(_009_),
    .Y(_002_[2])
  );
  NAND _155_ (
    .A(vc_assign[0]),
    .B(reset),
    .Y(_010_)
  );
  NOR _156_ (
    .A(edit_weight),
    .B(_010_),
    .Y(_000_[0])
  );
  NAND _157_ (
    .A(vc_assign[1]),
    .B(reset),
    .Y(_011_)
  );
  NOR _158_ (
    .A(edit_weight),
    .B(_011_),
    .Y(_000_[1])
  );
  NAND _159_ (
    .A(weight_vc2[0]),
    .B(_065_),
    .Y(_012_)
  );
  NAND _160_ (
    .A(_046_),
    .B(_012_),
    .Y(_013_)
  );
  NAND _161_ (
    .A(weight_vc0[0]),
    .B(_085_),
    .Y(_014_)
  );
  NOT _162_ (
    .A(_014_),
    .Y(_015_)
  );
  NOR _163_ (
    .A(_045_),
    .B(_054_),
    .Y(_016_)
  );
  NOR _164_ (
    .A(_015_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _165_ (
    .A(weight_vc1[0]),
    .B(_075_),
    .Y(_018_)
  );
  NAND _166_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _167_ (
    .A(_013_),
    .B(_019_),
    .Y(_020_)
  );
  NAND _168_ (
    .A(edit_weight),
    .B(_050_),
    .Y(_021_)
  );
  NAND _169_ (
    .A(reset),
    .B(_021_),
    .Y(_022_)
  );
  NOR _170_ (
    .A(_020_),
    .B(_022_),
    .Y(_001_[0])
  );
  NAND _171_ (
    .A(weight_vc3[1]),
    .B(_053_),
    .Y(_023_)
  );
  NOR _172_ (
    .A(_048_),
    .B(_066_),
    .Y(_024_)
  );
  NAND _173_ (
    .A(weight_vc1[1]),
    .B(_075_),
    .Y(_025_)
  );
  NAND _174_ (
    .A(weight_vc0[1]),
    .B(_085_),
    .Y(_026_)
  );
  NAND _175_ (
    .A(_025_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _176_ (
    .A(edit_weight),
    .B(_024_),
    .Y(_028_)
  );
  NAND _177_ (
    .A(_023_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _178_ (
    .A(_027_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _179_ (
    .A(edit_weight),
    .B(_051_),
    .Y(_031_)
  );
  NAND _180_ (
    .A(reset),
    .B(_031_),
    .Y(_032_)
  );
  NOR _181_ (
    .A(_030_),
    .B(_032_),
    .Y(_001_[1])
  );
  NAND _182_ (
    .A(weight_vc3[2]),
    .B(_053_),
    .Y(_033_)
  );
  NOR _183_ (
    .A(_049_),
    .B(_066_),
    .Y(_034_)
  );
  NAND _184_ (
    .A(weight_vc1[2]),
    .B(_075_),
    .Y(_035_)
  );
  NAND _185_ (
    .A(weight_vc0[2]),
    .B(_085_),
    .Y(_036_)
  );
  NAND _186_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _187_ (
    .A(edit_weight),
    .B(_034_),
    .Y(_038_)
  );
  NAND _188_ (
    .A(_033_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _189_ (
    .A(_037_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _190_ (
    .A(edit_weight),
    .B(_052_),
    .Y(_041_)
  );
  NAND _191_ (
    .A(reset),
    .B(_041_),
    .Y(_042_)
  );
  NOR _192_ (
    .A(_040_),
    .B(_042_),
    .Y(_001_[2])
  );
  always @(posedge clk)
      weight[0] <= _001_[0];
  always @(posedge clk)
      weight[1] <= _001_[1];
  always @(posedge clk)
      weight[2] <= _001_[2];
  always @(posedge clk)
      vc_id_out[0] <= _000_[0];
  always @(posedge clk)
      vc_id_out[1] <= _000_[1];
  always @(posedge clk)
      weight_vc0[0] <= _002_[0];
  always @(posedge clk)
      weight_vc0[1] <= _002_[1];
  always @(posedge clk)
      weight_vc0[2] <= _002_[2];
  always @(posedge clk)
      weight_vc1[0] <= _003_[0];
  always @(posedge clk)
      weight_vc1[1] <= _003_[1];
  always @(posedge clk)
      weight_vc1[2] <= _003_[2];
  always @(posedge clk)
      weight_vc2[0] <= _004_[0];
  always @(posedge clk)
      weight_vc2[1] <= _004_[1];
  always @(posedge clk)
      weight_vc2[2] <= _004_[2];
  always @(posedge clk)
      weight_vc3[0] <= _005_[0];
  always @(posedge clk)
      weight_vc3[1] <= _005_[1];
  always @(posedge clk)
      weight_vc3[2] <= _005_[2];
>>>>>>> eeb24d5af44f2a2f740465f22e4430c73a66e3c0
endmodule
