/* Generated by Yosys 0.7+560 (git sha1 d9a2b430, gcc 7.3.1 -fPIC -Os) */

module wrr_synth(reset, clk, weight, request_id, grant_id);
  input clk;
  output [1:0] grant_id;
  input [1:0] request_id;
  input reset;
  input [2:0] weight;
  assign grant_id = 2'h0;
endmodule
